Bonk Command
gurkult/gurkbot pull request #100
Opened 2021-03-07 07:01 UTC by ShakyaMajumdar

For #96

2021-03-07 08:48 UTC, v1nam commented
It would be better to move yodobonk.gif to resources/images or some other folder inside resources, so it can be organized when we decide for future image commands

2021-03-07 08:49 UTC, v1nam commented
Same with yodobonk.json, it should go into resources too

2021-03-07 08:49 UTC, ShakyaMajumdar commented
Alright

2021-03-07 08:51 UTC, ShakyaMajumdar commented
Should I put the json directly under resources? or with the gif in resources/images?

2021-03-07 08:52 UTC, v1nam commented
You can put it directly under resources

2021-03-07 09:06 UTC, ShakyaMajumdar commented
done

2021-03-08 09:47 UTC, gustavwilliam requested changes
Thanks; I like this command! There are a few things to look into, though, and I haven’t tested this yet. This is a pure code review.

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
Same here

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        await member.avatar_url_as(format="png").save("pfp.png")
Would it be possible to keep the file in memory (and return it) instead of physically saving it?

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +SMALL_MASK = Image.new("L", (SMALL_DIAMETER,) * 2)
Could you include a comment that mentions why there’s a small and large one? If a person who hasn’t used the command looks at this, they won’t know that “small mask” is the final step of the bonk.

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +white_bg = Image.new("RGBA", BONK_GIF.size, "WHITE")
Maybe `canvas` or similar would be more fitting? Right now, we don’t see any white in the finished gif.

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +    def _generate_gif() -> None:
Great that you’re using a helper method instead of shoving it all in the command!

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +            frame = bg.convert("RGBA")
`frame` is updated to mean something completely different here, which makes it a lot harder to follow the code. Right? If not, why is the background even used, and not just the original frame. I don’t quite follow.

2021-03-08 09:47 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +                            PFP_CENTRE[1] - SMALL_DIAMETER // 2 + 10,
Mention what the `+ 10` is supposed to do in a comment

2021-03-08 12:06 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await member.avatar_url_as(format="png").save("pfp.png")
I managed to do this successfully, using `member.avatar_url.read()` which gives a `bytes` object. 

Also, I had to introduce `functools.partial` so I could pass an argument with the `_generate_gif` method to `run_in_executor`.

Hence:
```py
pfp = await member.avatar_url.read()
func = functools.partial(self._generate_gif, pfp)
with concurrent.futures.ProcessPoolExecutor() as pool:
    await asyncio.get_running_loop().run_in_executor(pool, func)
```
I might need a better variable name for `func`, lol

2021-03-08 12:09 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
I still haven't figured out how I can return the gif instead of saving it; PIL doesn't seem to offer any way to create the gif without saving it. 

There might be another 3rd party module I could use, will have to hunt some more.

Alternatively, it could also be possible to have the file, but delete it after it's sent.

2021-03-08 12:12 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +SMALL_MASK = Image.new("L", (SMALL_DIAMETER,) * 2)
Added: 

```py
# Two masks, one for the normal size, and a smaller one for the final stage of the bonk
```

2021-03-08 12:14 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +white_bg = Image.new("RGBA", BONK_GIF.size, "WHITE")
Yeah.
Have changed the name to `canvas`.

2021-03-08 12:14 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    def _generate_gif() -> None:
:)

2021-03-08 12:15 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            frame = bg.convert("RGBA")
I agree, these are mostly remnants of something I was trying earlier with transparency. Did a small refactor to make it more readable.

2021-03-08 12:16 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +                            PFP_CENTRE[1] - SMALL_DIAMETER // 2 + 10,
Done

2021-03-08 23:43 UTC, Shivansh-007 requested changes

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +    async def bonk(self, ctx: commands.Context, member: discord.Member) -> None:
Please add a cool down on this command.

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        pfp = await member.avatar_url.read()
Trigger `await.ctx.typing()` here to let users know that the Image is getting processed and will be there soon.

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        with concurrent.futures.ProcessPoolExecutor() as pool:
Add a blank line above and below the `with` to keep the function clean.

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
Can we send the file in a embed? Like this 


![1B92332B-9095-4EAE-8F8E-A4B21284B1E5](https://user-images.githubusercontent.com/69356296/110396240-aadc9f80-8095-11eb-9658-a6f431fd3232.jpeg)

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/resources/yodabonk.json
> +{
I don’t think this should be added to resources, and should rather be constants on the file.

2021-03-08 23:43 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
Hmmm can we save it in `BytesIO` instance?

2021-03-09 03:54 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
I don't think so, it looks like PIL has absolutely nothing for writing gifs.

2021-03-09 03:55 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        with concurrent.futures.ProcessPoolExecutor() as pool:
Alright

2021-03-09 03:56 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
I'm not sure how a gif would look in an embed, I'll give it a shot anyways

2021-03-09 03:59 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        pfp = await member.avatar_url.read()
Done

2021-03-09 04:02 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    async def bonk(self, ctx: commands.Context, member: discord.Member) -> None:
Okay, what values should I put for:
- No. of times it can be used before the cooldown, and
- How long the cooldown should be?

And should the cooldown be applicable to everyone?

2021-03-09 04:12 UTC, ShakyaMajumdar commented on bot/resources/yodabonk.json
> +{
Fixed

2021-03-09 06:11 UTC, Shivansh-007 requested changes

2021-03-09 06:11 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +    async def bonk(self, ctx: commands.Context, member: discord.Member) -> None:
I think once in every `10` seconds seems fine.

2021-03-09 06:11 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        embed = discord.Embed(title=f"get bonkt {member.display_name}")
```suggestion
        embed = discord.Embed(title=f"Get bonkt {member.display_name}!")
```

2021-03-09 06:11 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
Instead of naming it out, can we name it as `bonk_{user_name}.gif`?

2021-03-09 06:11 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        """Command to send gif of mentioned member being bonked."""
Would be awesome if we can add a shortline telling what `getting bonked` means.

2021-03-09 06:13 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
Looks good in an embed, done

2021-03-09 06:16 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
hmm
I don't mind changing the name of the file, but won't having separate files for each user take up a lot of space? Each gif is ~3MB

2021-03-09 06:17 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
Like I said last time, we can store the image in a `BytesIO` instance.

2021-03-09 06:35 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        embed = discord.Embed(title=f"get bonkt {member.display_name}")
I disagree
imo, it is nice and informal the way it already is

2021-03-09 06:40 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +        """Command to send gif of mentioned member being bonked."""
I think it's fine the way it is, but imo  `"Sends gif of mentioned member being bonked."` is sufficient.

2021-03-09 07:01 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
Are you overwriting `out.gif` every time someone uses the command, @ShakyaMajumdar  ?

2021-03-09 07:03 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
Why don't you delete the gif after it's sent? There is no reason to keep it until another user uses the command and overwrites it.
I like @Shivansh-007 idea of giving it an informative name. How about `bonk_{user_name}_{timestamp}.gif` ?

2021-03-09 08:35 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        embed = discord.Embed(title=f"get bonkt {member.display_name}")
> I disagree
> imo, it is nice and informal the way it already is

Well this is not about how you feel, we need to follow English rules...
And `Get bonkt Jason!` looks better than `get bonked jason`. The exclamation mark adds some emotions to it, and `G` this is English rule.

2021-03-09 10:33 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
@codephile1221 
> Are you overwriting out.gif every time someone uses the command, @ShakyaMajumdar ?

Yeah.
> Why don't you delete the gif after it's sent

Yeah I thought of that too (https://github.com/gurkult/gurkbot/pull/100#discussion_r589374930), I think I'll do this.
If I'm deleting it anyway, the filename doesn't really matter 🥴, but I'll take the suggestion

2021-03-09 10:35 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
> I don't think so, it looks like PIL has absolutely nothing for writing gifs.

It has as far I remember, there is also a stackoverflow post on that. I will see if I can find it.

2021-03-09 10:38 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
File name will be useful if the user wants to download the gif for whatever reason.

2021-03-09 11:26 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    async def bonk(self, ctx: commands.Context, member: discord.Member) -> None:
Done

2021-03-09 11:26 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"), embed=embed)
Done

2021-03-09 12:21 UTC, Shivansh-007 requested changes
We can use `BytesIO` to save image, this is how you can do it:
```py
from io import BytesIO
from PIL import Image

im = Image.new("RGB", (50, 50))
data = BytesIO()
im.save(data, "gif")
data.seek(0)

# e.g. save to file
import shutil
with open("image.gif", "wb") as f:
    shutil.copyfileobj(data, f)
```

2021-03-09 12:26 UTC, ShakyaMajumdar commented
@Shivansh-007 what would be the benefit of doing this? Opposed to the Image.save in PIL?

Also, I don't see how I can use that to combine multiple images into 1 gif

2021-03-10 11:44 UTC, Shivansh-007 requested changes
Can we revert the changes done in `Pipfile.lock`? They aren't needed afaik.

2021-03-10 11:44 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +import concurrent.futures
```suggestion
from concurrent import futures
```
If we just need the `futures`, why not just do this?

2021-03-10 11:44 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +            with concurrent.futures.ProcessPoolExecutor() as pool:
```suggestion
            with futures.ProcessPoolExecutor() as pool:
```

2021-03-10 11:44 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +
No need of this empty line.

2021-03-10 11:44 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +            duration=50,
Can we make this a constant?

2021-03-10 11:44 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +        func = functools.partial(self._generate_gif, pfp)
We can group all these together, no need of new lines here.

2021-03-10 12:04 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            duration=50,
Which one?

2021-03-10 12:06 UTC, v1nam commented
> No clue why there were changes in Pipfile.lock, I didn't even touch the file lol
Pipfile.lock contains info on the pip packages installed, i believe you installed pillow through `pipenv install pillow`, that does change the Pipfile.lock and the Pipfile

2021-03-10 12:08 UTC, ShakyaMajumdar commented
Oh
Am I supposed to use `pip install ...`  instead of `pipenv install ...` then?

2021-03-10 12:17 UTC, v1nam commented
No

2021-03-10 12:18 UTC, v1nam commented
There is nothing wrong about the Pipfile.lock being changed, it would be a problem if it weren't change, which will break the docker build

2021-03-10 12:32 UTC, ShakyaMajumdar commented
I see

2021-03-10 12:36 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +import concurrent.futures
done

2021-03-10 12:36 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +
alright

2021-03-10 12:37 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        func = functools.partial(self._generate_gif, pfp)
Okay

2021-03-10 12:37 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            with concurrent.futures.ProcessPoolExecutor() as pool:
done

2021-03-10 13:28 UTC, gustavwilliam submitted a review, later dismissed
Excellent work on this! I have a few more comments, but it's looking pretty good.

(I misclicked, so it originally looked like I approved. Consider this review as "requested changes")

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +            out_images.append(canvas)
This could all be in a helper method, like `_generate_frame`, which would make things easier to follow and debug. Just call this method for every frame and generate them like usual.

Instead of using globals in this new helper, just pass arguments and return the image. I hope that makes sense!

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        pfps = [pfp.resize((LARGE_DIAMETER,) * 2), pfp.resize((SMALL_DIAMETER,) * 2)]
Could this be a dictionary? That would allow you to access the small frame through `pfp_sizes["small"]` or similar.

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +    @commands.max_concurrency(3)
Did you have a cooldown for it as well?

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        """Sends gif of mentioned member being bonked [whacked by Yoda]."""
```suggestion
        """Sends gif of mentioned member being "bonked" by Yoda."""
```
Being "whacked" by Yoda doesn't sound quite right. What do you think about this?

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        created_at = ctx.message.created_at.strftime("%Y-%m-%d_%H-%M-%S-%f")
Considering that we're saving to memory now, we can ignore some of the details in the file name. Just date (and hour/seconds, if you want to) should be enough.

2021-03-10 13:28 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +        embed = discord.Embed(title=f"Get bonkt {member.display_name}!")
```suggestion
        embed = discord.Embed(title=f"Get bonked, {member.display_name}!")
```
Not sure about this grammar. The comma should be there, though.

If we even want this phrase?

2021-03-10 13:34 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    @commands.max_concurrency(3)
I used to, but I removed it. Is it required?

2021-03-10 13:37 UTC, gustavwilliam commented on bot/exts/fun/bonker.py
> +    @commands.max_concurrency(3)
Like, 5 times per 60 seconds should be enough per person, IMO. What do you think?

2021-03-10 13:37 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        embed = discord.Embed(title=f"Get bonkt {member.display_name}!")
I think I should remove it altogether.

I had added it in the first place because I was under the impression that embeds must necessarily have titles. Since they don't, I think we could remove it.

2021-03-10 14:29 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        await ctx.send(file=discord.File("out.gif"))
Done, simply used a BytesIO object as a file-like object

2021-03-10 14:31 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        created_at = ctx.message.created_at.strftime("%Y-%m-%d_%H-%M-%S-%f")
Okay, keeping the username, date and time (hour:min) in the file name.

2021-03-10 16:57 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            out_images.append(canvas)
Done

2021-03-10 17:27 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    @commands.max_concurrency(3)
As discussed, the cooldown could be added later if required

2021-03-10 17:29 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        pfps = [pfp.resize((LARGE_DIAMETER,) * 2), pfp.resize((SMALL_DIAMETER,) * 2)]
Done

2021-03-10 17:30 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        """Sends gif of mentioned member being bonked [whacked by Yoda]."""
Think this is better, changed.

2021-03-11 00:16 UTC, Shivansh-007 commented on bot/exts/fun/bonker.py
> +            duration=50,
Yeah right, we can ignore this.

2021-03-11 00:21 UTC, Shivansh-007 requested changes
Just one change is required. Good Job! Really nicely done 😃

2021-03-11 00:21 UTC, Shivansh-007 commented on Pipfile
> +colorama = "*"
1. Remove both the changes in `Pipfile` and ‘Pipfile.lock`.
2. Run ‘pipenv install Pillow`
3. Add a definite version in place of `*`

Basically remove `colorama` and add a definite version.

2021-03-11 03:11 UTC, ShakyaMajumdar commented on Pipfile
> +colorama = "*"
I followed step 1 and step 2, but that removed `colorama` from Pipfile lol

2021-03-11 11:07 UTC, Shivansh-007 approved these changes
Everything looks good, just not sure about the `Pipfile.lock`.

2021-03-12 17:23 UTC, RandomDev26 approved these changes
LGTM

2021-03-22 08:51 UTC, codephile1221 requested changes

2021-03-22 08:51 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +        out_filename = f"bonk_{member.display_name}_{created_at}.gif".replace(" ", "")
The embed still breaks if the display name has `/` or `\`, or any other special characters.

2021-03-22 11:21 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        out_filename = f"bonk_{member.display_name}_{created_at}.gif".replace(" ", "")
fixed, using id instead of display_name

2021-03-22 13:58 UTC, codephile1221 requested changes
Final review 🤞

2021-03-22 13:58 UTC, codephile1221 commented on bot/exts/fun/bonker.py
> +    def _generate_gif(self, pfp: bytes) -> BytesIO:
You can log that a gif is being generated here (trace level), and maybe also log that a gif has been generated at the end of this method.

2021-03-22 14:18 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +        i: int, frame: Image.Image, pfps_by_size: Dict[str, int]
Done

2021-03-22 14:19 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            out_images.append(self._generate_frame(i, frame, pfps_by_size))
Done

2021-03-22 14:19 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +    def _generate_gif(self, pfp: bytes) -> BytesIO:
Done

2021-03-22 14:22 UTC, codephile1221 approved these changes
LGTM 👍 
We will watch your career with great interest.

2021-03-22 15:05 UTC, merged