Feature/make_gurkan
gurkult/gurkbot pull request #101
Opened 2021-03-07 23:19 UTC by RandomDev26

Closes #32

2021-03-07 23:52 UTC, gustavwilliam requested changes
Thanks! This looks pretty good, but I have a few comments to resolve.

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +    """Make Gurkan Cog adds or removes the gurkan role depending on if the user has gurkan in their name."""
```suggestion
    """Makes sure that only members with gurkan names have the gurkan role."""
```
Let's make it a bit more concise.

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +        Adds/Removes the role on member update.
```suggestion
        Adds/Removes the gurkan role on member update.
```
More specific.

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +            if re.search(r"gurk|urkan", str(after.display_name)):
Let's use the function for checking gurkans, that's already defined in utils.

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +                await after.remove_roles(role)
What if they start out with a gurkan nickname and end on a new, but still gurkan, nickname? Will this just be ignored and still work out?

The same thing if they aren't gurkan and end up not being gurkan either.

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +        """When the member joins, this function will check if member is classified to be a gurkan or not."""
```suggestion
        """Adds the gurkan role to new members who are classified as gurkans."""
```
Concise!

2021-03-07 23:52 UTC, gustavwilliam commented on bot/exts/gurkan/make_gurkan.py
> +        if re.search(r"gurk|urkan", str(member.name)):
```suggestion
        if re.search(r"gurk|urkan", str(member.display_name)):
```
I see no reason to not use the display name. If they've joined before, had a gurkan nickname and are rejoining, will the nickname be left? I don't know, but I'd rather not risk it.

2021-03-07 23:55 UTC, RandomDev26 commented on bot/exts/gurkan/make_gurkan.py
> +        if re.search(r"gurk|urkan", str(member.name)):
Yea, display name would be better.

2021-03-08 00:33 UTC, gustavwilliam approved these changes
LGTM! Thanks.

I haven't tested this, but the code looks good.

2021-03-08 00:38 UTC, vivax3794 commented on Pipfile
> +flake8 = "*"
why where these added, I dont see them mentioned in the added imports?

2021-03-08 00:40 UTC, RandomDev26 commented on Pipfile
> +flake8 = "*"
When running it on windows, it requires that those be installed

2021-03-08 00:42 UTC, vivax3794 commented on Pipfile
> +flake8 = "*"
I dont see how any of those 2 are required to run the bot, maybe I am missing something?

2021-03-08 00:47 UTC, RandomDev26 commented on Pipfile
> +flake8 = "*"
It required me to install flake8 for linting, and win32-setctime is needed by loguru.

2021-03-08 00:50 UTC, vivax3794 commented on Pipfile
> +flake8 = "*"
flake8 would have been installed when you do a dev-install (you see it is listed under dev-dependencies) `pipenv sync --dev`

and I would have assumed `win32-setctime` would have been automatically installed if it is a dependency of `loguru`? but I guess I am wrong.

2021-03-08 00:51 UTC, RandomDev26 commented on Pipfile
> +flake8 = "*"
IDK, maybe I messed up while installing all the dependencies. Should I remove it?

2021-03-08 00:53 UTC, vivax3794 commented on Pipfile
> +flake8 = "*"
flake8 you can remove, I would assume you could remove `win32-setctime`, but I cant't test that as I am not on windows

2021-03-08 03:32 UTC, Shivansh-007 requested changes

2021-03-08 03:32 UTC, Shivansh-007 commented on Pipfile
> +flake8 = "*"
Also be specific `*` is not acceptable.

2021-03-08 04:23 UTC, RandomDev26 commented on Pipfile
> +flake8 = "*"
Done!

2021-03-08 04:24 UTC, RandomDev26 commented
I'm bad at pipenvs, but I think I fixed it now

2021-03-08 06:08 UTC, Shivansh-007 requested changes
Can you reset all the changes in `Pipfile` and `Pipfile.lock`. They aren't needed.

2021-03-08 06:09 UTC, RandomDev26 commented
Uhhh... How do I do that?

2021-03-08 06:21 UTC, RandomDev26 commented
@Shivansh-007 done!

2021-03-08 06:30 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-03-08 07:16 UTC, vivax3794 approved these changes
LGTM

2021-03-08 07:25 UTC, codephile1221 commented
Hello there, looks good to me!

2021-03-08 07:26 UTC, codephile1221 approved these changes
Hello there, looks good to me!

2021-03-08 07:28 UTC, merged