Add color command
gurkult/gurkbot pull request #103
Opened 2021-03-08 13:47 UTC by v1nam

Currently this is the output for this command #102
![image](https://user-images.githubusercontent.com/71541684/110329555-c4a0c700-8042-11eb-9553-152491576903.png)
![image](https://user-images.githubusercontent.com/71541684/110329584-ccf90200-8042-11eb-8a8a-5c286609dd22.png)

2021-03-08 14:06 UTC, gustavwilliam requested changes
Thanks! Looks *great*. I'm looking forward to seeing this on gurkbot.

2021-03-08 14:06 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +        """Command for sending an image which is the color of provided as the input."""
```suggestion
        """Sends an image which is the color of provided as the input."""
```
If we look at the full list of commands, we already know it's a command. Let's make it a bit more direct.

2021-03-08 14:06 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +            file = File(bufferio, filename="color.png")
```suggestion
            file = File(bufferio, filename=f"{color_code}.png")
```
Could we make the filename the hex color code? Makes more sense imo.

2021-03-08 21:48 UTC, RandomDev26 requested changes

2021-03-08 21:48 UTC, RandomDev26 commented on Pipfile
> +pillow = "*"
Can you specify the version?

2021-03-08 21:48 UTC, RandomDev26 commented on bot/exts/utils/color.py
> +            await ctx.send(f"Unknown color specifier '{color_code}'")
I think the color code should be in a code block, not a single quote
```suggestion
            await ctx.send(f"Unknown color specifier `{color_code}`")
```

2021-03-08 23:35 UTC, Shivansh-007 requested changes

2021-03-08 23:35 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            Get a visual picture for color given as input, valid formats are \
I don’t think we need a help doc-string overwriting. Can you put this ass the function’s doc-string, since I don’t see any difference between the two, and why we should keep two of them.

2021-03-08 23:35 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +    """The Color cog containing a parser function for parsing the colors and the command function."""
I don’t think "The Color cog" is needed, since we can already understand that from the line above.

2021-03-09 04:09 UTC, v1nam commented on bot/exts/utils/color.py
> +    """The Color cog containing a parser function for parsing the colors and the command function."""
uhm well all the doc strings are just there because of flake 8

2021-03-09 04:10 UTC, v1nam commented on bot/exts/utils/color.py
> +    """The Color cog containing a parser function for parsing the colors and the command function."""
except i would only keep the help kwarg

2021-03-09 05:42 UTC, RohanJnr commented on bot/exts/utils/color.py
> +    """The Color cog containing a parser function for parsing the colors and the command function."""
he means the doc string could be `A cog containing a parser function for parsing the colors and the command function.`

2021-03-09 05:46 UTC, RohanJnr commented on bot/exts/utils/color.py
> +from discord.ext.commands import Cog, Context, command
```suggestion
from discord import File
from discord.ext.commands import Bot, Cog, Context, command
from PIL import Image
```

2021-03-09 05:47 UTC, RohanJnr commented on bot/exts/utils/color.py
> +        """Function for parsing a color code string to its respective mode."""
```suggestion
        """Parse a color code string to its respective mode."""
```

2021-03-09 05:48 UTC, v1nam commented on bot/exts/utils/color.py
> +from discord.ext.commands import Cog, Context, command
flake8 wants uppercase modules to be on top, maybe because their ascii code values come before lowercase ones

2021-03-09 05:58 UTC, RohanJnr commented on bot/exts/utils/color.py
> +            file = File(bufferio, filename="color.png")
Not sure if we need such a huge a try block, maybe try to slim it down to the line which could cause the error.

2021-03-09 05:59 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +    """The Color cog containing a parser function for parsing the colors and the command function."""
Yes! @RohanJnr is right!

2021-03-09 06:06 UTC, Shivansh-007 requested changes

2021-03-09 06:06 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +class Color(Cog):
```suggestion
class ColorVisualizer(Cog):
```
Seems a more appropriate name.

2021-03-09 06:06 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
Can we send this as a embed, with the embed colour as the color specified by the user and the file contained in the embed.

2021-03-09 06:06 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            file = File(bufferio, filename="color.png")
`new_col = Image.new("RGB", (128, 128), color_code)` Just keep this line inside the `try...except` block.

2021-03-09 06:06 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +    bot.add_cog(Color(bot))
```suggestion
    """Load the ColorVisualizer cog."""
    bot.add_cog(ColorVisualizer(bot))
```

2021-03-10 08:52 UTC, anand2312 commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
An embed's color is the small little colored bar on it's left side. Using it as the image of the embed would be better.

2021-03-10 09:09 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
This is what I meant:
![Screenshot from 2021-03-10 14-38-38](https://user-images.githubusercontent.com/69356296/110604679-57aa4000-81ae-11eb-9422-c098e1a36cbb.png)

2021-03-10 09:28 UTC, anand2312 commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
Yep, just making sure

2021-03-10 09:32 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +            Get a visual picture for color given as input, valid formats are \
I think this is fine. The docstring is nice while just working on this as code.

2021-03-10 09:33 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            Get a visual picture for color given as input, valid formats are \
I don’t see a need to write two docsteings when you need to convey the same information.

2021-03-10 09:36 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +class Color(Cog):
Maybe. It's longer and to be frank, it feels like bikeshedding at this point. Let's just use `Color`.

2021-03-10 09:36 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +    bot.add_cog(Color(bot))
Same here.

2021-03-10 09:37 UTC, codephile1221 commented on bot/exts/utils/color.py
> +            Get a visual picture for color given as input, valid formats are \
I agree with @Shivansh-007, I feel this help text should be used as the doc-string too.

2021-03-10 09:37 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +class Color(Cog):
`Color` is the name of our class in constants storing the colours, so it is better to keep it more specific.

2021-03-10 09:38 UTC, gustavwilliam commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
I generally love using embeds, but does it really look better in this case? Either way, if we do, let's just make `#XXXXXX` the title, where XXXXXX is the hex color value.

2021-03-10 09:40 UTC, Shivansh-007 commented on bot/exts/utils/color.py
> +            await ctx.send(file=file)
Yeah make that the title and it will look good!

2021-08-01 03:17 UTC, v1nam commented
closing this, due to issues fork has been changed so creating new PR

2021-08-01 03:17 UTC, closed without merging