Postgres DB setup
gurkult/gurkbot pull request #107
Opened 2021-03-13 17:08 UTC by RohanJnr

closes #93 

- Setup postgres database using docker compose.
- Connect to postgres DB with asyncpg.
- Add utility methods and entry point for DB tables.

2021-03-29 10:48 UTC, Shivansh-007 requested changes
Quick first review.

2021-03-29 10:48 UTC, Shivansh-007 commented on bot/bot.py
> +        await Tortoise.close_connections()
There should be a if statement on this, in case, the db init fails, and the db is not setup.

2021-03-29 10:48 UTC, Shivansh-007 commented on bot/exts/fun/off_topic.py
> +            await ctx.send(f"`{name}` not found!")
Ok :x: emoji is necessary!!!!!!!!
```suggestion
            await ctx.send(f":x:`{name}` not found!")
```

2021-04-05 16:22 UTC, RohanJnr commented on bot/bot.py
> +        await Tortoise.close_connections()
I don't think so, the source code does not show signs of any error if connections are 0
```python
@classmethod
    async def close_connections(cls) -> None:
        """
        Close all connections cleanly.

        It is required for this to be called on exit,
        else your event loop may never complete
        as it is waiting for the connections to die.
        """
        tasks = []
        for connection in cls._connections.values():
            tasks.append(connection.close())
        await asyncio.gather(*tasks)
        cls._connections = {}
        logger.info("Tortoise-ORM shutdown")```

2021-04-05 17:05 UTC, Shivansh-007 commented on bot/bot.py
> +        await Tortoise.close_connections()
Right, this can probably be ignored then.

2021-04-17 20:37 UTC, gustavwilliam requested changes
This looks great! I have a few minor comment, but it's looking really cool.

This is only a code review.

2021-04-17 20:37 UTC, gustavwilliam commented on bot/bot.py
> +
```suggestion
```
Maybe this line can be removed?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/bot.py
> +    async def notify_dev_alert(
Should this be before the `_db_setup` function, so it's defined before it's used. This won't change the way the code works, but might be a bit clearer

2021-04-17 20:37 UTC, gustavwilliam commented on bot/converters.py
> +    Taken from python-discord/bot https://github.com/python-discord/bot/blob/master/bot/converters.py#L344
```suggestion
    Adapted from python-discord/bot https://github.com/python-discord/bot/blob/master/bot/converters.py#L344
```
This might be more fitting

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +CROSS_MARK_EMOJI = "\U0000274C"
You could also use the unicode emojis straight in the code. Like just ❌ and ✅

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +    use_db = True
What is this? Maybe you could add a comment in the code to clarify.

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        self.ot_channel: TextChannel = ...
What is the ellipsis `...` doing here? And on the line below.

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        )
Should this really be a part of the cache function? Shouldn't it be set up in the init function directly?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +
Could we delete the "similar ot names" embed here, or update that one instead of sending a new message?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        # ot_ins = await OT_Model.create(name=name)
Should this be removed?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        await ctx.send(f":ok_hand: `{name}` has been added!")
Could we send this in an embed as well?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +                await ctx.send(f"Off topic name `{name}` not added.")
Could we send this in an embed? I love embeds on gurkbot

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        # )
```suggestion
```
Should this be removed?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +            await ctx.send(f":x: `{name}` not found!")
Embed?

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +                await self._send_paginated_embed(ctx, names, "Did you mean ❓")
```suggestion
                await self._send_paginated_embed(ctx, names, "Did you mean one of the following?")
```
Maybe something like this? I don't love the ❓.

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        await ctx.send(f"`{name}` has been deleted :white_check_mark:")
Embed!

2021-04-17 20:37 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +            while f"ot-{name}" == self.ot_channel.name:
Could `ot-` be in a separate value, since you're using it in two places? (Check line 196)

Also, let's use `｜` instead of `-` (notice that it's ｜ and not |. These are two different characters)

2021-04-18 06:41 UTC, gustavwilliam commented
@Akarys42 would you like to review this as well? If you have time.

2021-04-18 12:53 UTC, Akarys42 requested changes
The PR looks pretty good to me, a few minor suggestions.

2021-04-18 12:53 UTC, Akarys42 commented on bot/converters.py
> +    Taken from python-discord/bot https://github.com/python-discord/bot/blob/master/bot/converters.py#L344
This should also mention the license and copyright

2021-04-18 12:53 UTC, Akarys42 commented on bot/converters.py
> +        table = str.maketrans(allowed_characters, "𝖠𝖡𝖢𝖣𝖤𝖥𝖦𝖧𝖨𝖩𝖪𝖫𝖬𝖭𝖮𝖯𝖰𝖱𝖲𝖳𝖴𝖵𝖶𝖷𝖸𝖹ǃ？’’-")
`table` can be a class attribute to avoid recreating it every time.

2021-04-18 12:53 UTC, Akarys42 commented on bot/exts/fun/off_topic.py
> +CROSS_MARK_EMOJI = "\U0000274C"
It should be avoided since it can cause Unicode errors. Unicode points are what I usually recommend.

2021-04-18 12:53 UTC, Akarys42 commented on bot/exts/fun/off_topic.py
> +            ctx, self._find(name), f"🔎 Search result: {name}"
It should use the Unicode point
```suggestion
            ctx, self._find(name), f"\U0001f50e Search result: {name}"
```

2021-04-18 12:53 UTC, Akarys42 commented on bot/exts/fun/off_topic.py
> +            or fuzz.partial_ratio(ot_name, name) == 100
80 and 100 should be constants

2021-04-18 12:53 UTC, Akarys42 commented on bot/exts/fun/off_topic.py
> +    async def update_ot_channel_name(self) -> None:
Should it be possible to have the bot send an embed in the off-topic channel saying what the new name is?

2021-04-18 13:58 UTC, RohanJnr commented on bot/converters.py
> +    Taken from python-discord/bot https://github.com/python-discord/bot/blob/master/bot/converters.py#L344
in any specific format?

2021-04-18 14:00 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +    use_db = True
Oh, that's not meant to be there. I forgot to remove it after testing something.

2021-04-18 14:01 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        self.ot_channel: TextChannel = ...
Using it like a pass instead of None.

2021-04-18 14:02 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        )
Well, the func also needs to wait until the guild cache is ready. That's why I am calling `await self.bot.wait_until_ready()` before this line

2021-04-18 14:03 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +
I think deleting it will be better.

2021-04-18 14:04 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        # ot_ins = await OT_Model.create(name=name)
yep!

2021-04-18 14:09 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        await ctx.send(f":ok_hand: `{name}` has been added!")
I'm not sure if it will look good to use embeds for a single sentence? 🤔

2021-04-18 15:37 UTC, gustavwilliam commented
Did you test the PR?

2021-04-20 13:21 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +CROSS_MARK_EMOJI = "\U0000274C"
What kind of errors are you referring to?

2021-04-20 13:23 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +        await ctx.send(f":ok_hand: `{name}` has been added!")
I think it looks pretty good, considering that everything else on the bot uses embeds. It’s more about consistency.

2021-04-20 14:28 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        await ctx.send(f":ok_hand: `{name}` has been added!")
alright then

2021-04-21 04:56 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +CROSS_MARK_EMOJI = "\U0000274C"
Using unicode emojis would crash IDLE, my favorite text editor.

2021-04-21 05:14 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +CROSS_MARK_EMOJI = "\U0000274C"
I see. We must be respectful to the sweet IDLE-users that are making advanced Discord bots.

2021-04-21 06:39 UTC, codephile1221 requested changes
I have not tested the code.

2021-04-21 06:39 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +    @off_topic_names.command(name="find", aliases=("f", "search"))
```suggestion
    @off_topic_names.command(name="find", aliases=("f", "s", "search"))
```

2021-04-21 06:39 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +        )
I would hoist these methods. Can you move them under the [`_cache` method](https://github.com/gurkult/gurkbot/pull/107/files#diff-834e9a52deb3a5442ed0d2f39d4b83085c306fad41467adfda84fea1b91762b3R37)?

2021-04-21 06:39 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +        )
`_send_paginated_embed` too. (https://github.com/gurkult/gurkbot/pull/107/files#diff-834e9a52deb3a5442ed0d2f39d4b83085c306fad41467adfda84fea1b91762b3R151)

2021-04-21 06:39 UTC, codephile1221 commented on bot/converters.py
> +            raise BadArgument("Channel name must be between 2 and 96 chars long")
```suggestion
        if not (2 <= len(argument) <= 29):
            raise BadArgument("Channel name must be between 2 and 29 chars long")
```
This is giving me mixed signals.
I also don't mind restricting the off-topic name to a set length, like 20 or something.

2021-04-21 20:09 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        )
Aren't python `methods` already hoisted? I don't think we have a problem with hoisting when it comes to methods.

2021-04-21 20:13 UTC, RohanJnr commented on bot/converters.py
> +            raise BadArgument("Channel name must be between 2 and 96 chars long")
I think 20 would be quite short. example: `vester-is-not-a-gurkan`(sorry vester, just an example xD) is 22 chars long (and I think we will have such long OT names).

2021-04-22 05:29 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +        )
lol, my bad- poor choice of words.
By "hoisting", I wasn't referring to scope and all that stuff.
Moving these "private" methods up improves the structure of the code IMO.  I get to see the method's body before it get's used. Currently, it's in a weird spot in the middle of the file.

2021-04-25 19:21 UTC, gustavwilliam requested changes
This is looking great. Just a few final comments.

2021-04-25 19:21 UTC, gustavwilliam commented on bot/converters.py
> +
```suggestion
```
No need for a space here.

2021-04-25 19:21 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +            await asyncio.sleep(30)
```suggestion
            await asyncio.sleep(till_midnight)
```
Shouldn't this be waiting until midnight?

2021-04-25 19:21 UTC, gustavwilliam commented on bot/exts/fun/off_topic.py
> +                    title="Today's Off-Topic Name !",
```suggestion
                    title="Today's Off-Topic Name!",
```

2021-04-25 21:38 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +            await asyncio.sleep(30)
oh right, I was testing it, forgot to change it

2021-04-26 02:58 UTC, anand2312 commented on bot/exts/fun/off_topic.py
> +            await asyncio.sleep(30)
Why aren't you using `discord.utils.sleep_until` here?

2021-04-26 03:03 UTC, anand2312 commented on bot/postgres/utils.py
> +async def db_execute(pool: Pool, sql_statement: str, *args) -> None:
What is the reason for this design choice (as opposed to directly using the functions provided by the pool)? Is it just to add logging?
I feel like the docstring needn't mention the SQL statements you'd use with this either, as it's not easy to generalize like this. (For example, you would need to use `fetch` with an INSERT/UPDATE statement that had a RETUENING clause specified)

2021-04-26 04:56 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +            await asyncio.sleep(30)
oh, that could be handy, I will use that instead 👍

2021-04-26 05:02 UTC, RohanJnr commented on bot/postgres/utils.py
> +async def db_execute(pool: Pool, sql_statement: str, *args) -> None:
I made this as a utility statement for avoid code repeation for simple exec queries. Althought, I just created it as I needed it for the off topic names, we can add more utility methods based on use cases. Since the off topic cog is the only one using the database now, I have created those functions based on my use cases in the cog. Maybe the db fetch isn't used all that much, but prolly could be handy for other features.

I think you are right with the doc string part, I will remove them 👍

2021-04-28 08:09 UTC, gustavwilliam approved these changes
LGTM! Thanks for making this.

2021-04-28 08:16 UTC, anand2312 commented on bot/postgres/utils.py
> +async def db_execute(pool: Pool, sql_statement: str, *args) -> None:
Sorry for the late response;
I just asked because it seemed like a function that would end up being used often (fetch and execute will probably be used a lot later), so was wondering if putting it as a `util` and not part of the main `postgres` module looked a little off to me, but I can understand the rationale

2021-04-28 09:19 UTC, RohanJnr commented on bot/postgres/utils.py
> +async def db_execute(pool: Pool, sql_statement: str, *args) -> None:
it is under utils within the postgres folder.

2021-05-01 17:08 UTC, Akarys42 approved these changes
LGTM

2021-05-01 17:10 UTC, merged