Remove embed from bonk command output
gurkult/gurkbot pull request #112
Opened 2021-04-01 16:37 UTC by ShakyaMajumdar

As per the decision of #polls, the embed has been done away with.

F.

2021-04-01 16:54 UTC, Arnav-2004 requested changes

2021-04-01 16:54 UTC, Arnav-2004 commented on bot/exts/fun/bonker.py
> +            await ctx.send(file=discord.File(out_gif, out_filename))
Can you un-indent it by one?

2021-04-01 16:55 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            await ctx.send(file=discord.File(out_gif, out_filename))
It's intentional, it's so that the bot appears to be typing while sending the file too (which takes non-negligible time).

2021-04-01 16:57 UTC, Arnav-2004 commented on bot/exts/fun/bonker.py
> +            await ctx.send(file=discord.File(out_gif, out_filename))
If you un-indent it by one the bot will still appear to be typing, but you are correct it won't make much difference.

2021-04-01 16:58 UTC, ShakyaMajumdar commented on bot/exts/fun/bonker.py
> +            await ctx.send(file=discord.File(out_gif, out_filename))
if unindented it won't be typing while the file is being sent, it'll be typing during the gif generation.

2021-04-01 17:00 UTC, Arnav-2004 commented on bot/exts/fun/bonker.py
> +            await ctx.send(file=discord.File(out_gif, out_filename))
Oh yea correct, my bad

2021-04-01 17:04 UTC, Arnav-2004 approved these changes
LGTM!

2021-04-06 11:41 UTC, codephile1221 approved these changes
Looks good to me ⭐

2021-04-07 12:15 UTC, gustavwilliam approved these changes
LGTM.

2021-04-07 12:15 UTC, merged