LinePaginator
gurkult/gurkbot pull request #114
Opened 2021-04-05 02:04 UTC by Shivansh-007

Adds line pagination.

2021-04-06 14:31 UTC, RohanJnr requested changes
Initial review, tested and works well 👍

2021-04-06 14:31 UTC, RohanJnr commented on bot/utils/pagination.py
> +            if allow_empty_lines:
error out if `allow_empty_lines` is `False`.
```suggestion
            if not allow_empty_lines:
```

2021-04-06 14:31 UTC, RohanJnr commented on bot/utils/pagination.py
> +        is still exceeded, the excess characters are stored and placed on the next pages unti
```suggestion
        is still exceeded, the excess characters are stored and placed on the next pages until
```

2021-04-06 14:31 UTC, RohanJnr commented on bot/utils/pagination.py
> +        if len(line) > (max_chars := self.max_size - len(self.prefix) - 2):
what is the `-2` for?

2021-04-06 14:31 UTC, RohanJnr commented on bot/utils/pagination.py
> +    def _split_remaining_words(
staticmethod

2021-04-06 14:31 UTC, RohanJnr commented on bot/utils/pagination.py
> +        if self.max_lines is not None and self._line_count >= self.max_lines:
This will also handle if `self.max_lines` is `0`, treating 0  as None
```suggestion
        if self.max_lines and self._line_count >= self.max_lines:
```

2021-04-11 06:04 UTC, ShakyaMajumdar commented on bot/utils/pagination.py
> +        lines: t.List[str],
Just one small thing - I don't think having it as a List is necessary, `t.Iterable`/`t.Sequence` should be fine.

2021-04-11 06:07 UTC, ShakyaMajumdar commented on bot/utils/pagination.py
> +        lines: t.List[str],
Oh you're using append later, ignore this then

2021-04-11 06:07 UTC, ShakyaMajumdar commented
LGTM 👍

2021-04-11 06:30 UTC, RohanJnr approved these changes

2021-04-11 06:53 UTC, ShakyaMajumdar approved these changes

2021-04-11 07:07 UTC, gustavwilliam commented
Lovely to see some reviews coming in! Have you tested this @ShakyaMajumdar @RohanJnr? It’s totally fine if not, but I need to know before merging 😄

2021-04-11 07:09 UTC, ShakyaMajumdar commented
> Lovely to see some reviews coming in! Have you tested this @ShakyaMajumdar @RohanJnr? It’s totally fine if not, but I need to know before merging 😄

Yep, tested and works fine for me.

2021-04-11 07:12 UTC, RohanJnr commented
> Lovely to see some reviews coming in! Have you tested this @ShakyaMajumdar @RohanJnr? It’s totally fine if not, but I need to know before merging 😄

works fine

2021-04-11 07:15 UTC, gustavwilliam commented
Perfect, thanks. I’ll merge!

2021-04-11 07:15 UTC, merged

2021-04-11 09:08 UTC, codephile1221 reviewed
Here are a few stuff.
I think many of the debug logging statements are better off as trace logging. 



woah, the PR got merged, I wonder what'll happen to these reviews.

2021-04-11 09:13 UTC, gustavwilliam commented
Not much will happen with the reviews. Still, maybe we could update the code to your reviews? @codephile1221 @Shivansh-007 Would you like to create a new PR to update/refine this, or do you have any other ideas?

2021-04-11 10:02 UTC, Shivansh-007 commented on bot/constants.py
> +    trashcan = str(os.getenv("EMOJI_TRASHCAN", "<:trash:798179380626587658>"))
If the user doesn't have a :trash: emoji on their server, i.e. the bot is not able to get the emoji with the specified ID, then the pagination would error out, and thus the pagination won't work.

2021-04-11 10:08 UTC, codephile1221 commented on bot/constants.py
> +    trashcan = str(os.getenv("EMOJI_TRASHCAN", "<:trash:798179380626587658>"))
Don't you think using the default trashcan emoji is better in that case?

2021-04-11 10:09 UTC, codephile1221 commented on bot/constants.py
> +    trashcan = str(os.getenv("EMOJI_TRASHCAN", "<:trash:798179380626587658>"))
...if this  emoji-trashcan emoji is not in the server.

2021-04-11 10:10 UTC, RohanJnr commented on bot/constants.py
> +    trashcan = str(os.getenv("EMOJI_TRASHCAN", "<:trash:798179380626587658>"))
its the user's responsibility to define the trashcan emoji ID in their env file