Run linting workflow only on pushes to main branch or pull requests.
gurkult/gurkbot pull request #115
Opened 2021-04-05 02:38 UTC by Shivansh-007

We don't want to build, lint (and deploy - In Future) on every branches, and currently the `Build` works after `Linting` which runs on every pull request or push to master, hence even running the `Build` workflow.

The reasons for not running them are:

- They are run twice.
  - In case of forks: On the pull request and the branch (mainly people push from separate branches, and not `main`)
  - In case of main: On the branch and the pull request.

2021-04-07 12:19 UTC, gustavwilliam commented
Not sure why we wouldn’t want to run it on branches. It doesn’t cost us anything, and I’d like us to have linted and working code on all branches.

Could you give a second opinion here @Akarys42?

2021-04-07 12:21 UTC, dawnofmidnight commented
I agree. We want clean code everywhere. We don't want to have to deal with messy code later, it's best that it remain how it is in my opinion.

2021-04-07 12:29 UTC, Shivansh-007 commented
I agree with that, but there is no reason to build docker images on forks and other branches.

2021-04-07 12:31 UTC, dawnofmidnight commented
> I agree with that, but there is no reason to build docker images on forks and other branches.

I think doing it on all branches + all pull requests is best. Because there's no reason to do it on forks if they're not going to be used.

2021-04-07 12:32 UTC, Shivansh-007 commented
Why should it run on other branches? Docker images are mainly used for production use only and I don't see a reason to pull a branch, which is still in development.

2021-04-07 12:33 UTC, dawnofmidnight commented
Do we need the full docker image though? What if we only use the docker image on main, and just lint everywhere else?

2021-04-07 12:42 UTC, codephile1221 commented
> I agree with that, but there is no reason to build docker images on forks and other branches.

I guess it's to ensure that the build doesn't break when we use it in production, but I am not sure.

2021-04-07 12:44 UTC, Shivansh-007 commented
We have pull requests which are used to merge anything to main, and build action are ran on them.

2021-04-07 12:49 UTC, gustavwilliam commented
What's that supposed to mean?

2021-04-07 12:53 UTC, Akarys42 commented
The problem with linking on pushes *and* pull requests is that if you push a commit that also have a pull request opened you’d lint it twice. While we are billed for that, I’d rather avoid it when possible.

That said, there are smarter ways like only linting commits on pushes if there aren’t on a PR (skip otherwise). I’d prefer to see that here, what do you think @gustavwilliam ?

2021-04-07 12:54 UTC, Shivansh-007 commented
> The problem with linking on pushes and pull requests is that if you push a commit that also have a pull request opened you’d lint it twice. While we are billed for that, I’d rather avoid it when possible.

Well here it is, Akarys put it in better words than what I said in the PR description.

2021-04-07 12:57 UTC, gustavwilliam commented
I don't quite follow. When do you mean that it would lint twice?

2021-04-07 13:04 UTC, gustavwilliam commented
Ah, I see, thanks. That does sound unnecessary.

It also seems like this PR won't solve that issue, right? I'm not sure what the best method would be, but I trust your judgment.

2021-04-07 13:06 UTC, Akarys42 commented
This PR solves this issue, assuming that we don’t open PRs from the main branch, although it will stop linting of branches without a PR open with is pretty sad. That’s why I think we should be smarter about it and skip the push trigger if there’s a PR opened for this branch, should be fairly easy to do.

2021-04-07 13:10 UTC, gustavwilliam commented
I'm not in favor of stopping limiting on branches without a PR, just to fix that issue. Your proposed solution sounds much cleaner imo.

Could you open an issue/pr detailing what there is to be done? Maybe you, Jason or someone else would like to implement it?

2021-05-12 05:55 UTC, Shivansh-007 commented
@Akarys42 Are you willing to implement it?

2021-05-20 08:21 UTC, Akarys42 commented
I don’t have much free time right now but GitHub recently added a `concurrency` key to workflows which is designed for this.

Announcement blog: https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

2021-05-20 08:22 UTC, Akarys42 requested changes
See my previous comment, we should instead implement the `concurrency` setting.

2021-05-20 08:57 UTC, Akarys42 requested changes

2021-05-20 08:57 UTC, Akarys42 commented on .github/workflows/linting.yml
> +  group: ${{ github.ref }}
You have to add the workflow name here, otherwise push_container can be canceled by this one.

2021-05-20 10:21 UTC, Akarys42 approved these changes

2021-05-20 10:22 UTC, merged