Mod toolkit stage 1: logs
gurkult/gurkbot pull request #117
Opened 2021-04-18 14:28 UTC by Akarys42

This PR adds our greatly needed #logs and #dm-log channels

2021-04-18 15:09 UTC, vcokltfre requested changes

2021-04-18 15:09 UTC, vcokltfre commented on bot/exts/moderation/logs.py
> +        color: int = Colours.green,
Would it perhaps make more sense here to use `colour` rather than `color` for consistency and minimal confusion, since that's the spelling of the constant

2021-04-18 15:09 UTC, vcokltfre commented on bot/exts/moderation/logs.py
> +            f"edited a message in #{after.channel}.",
Perhaps here it would make sense to use channel.mention to get the actual mention rather than simply using the channel name prefixed by a #?

2021-04-18 15:09 UTC, vcokltfre commented on bot/exts/moderation/logs.py
> +                title=f"Direct message from {message.author.name}#{message.author.discriminator}",
Putting `message.author` directly into the f-string should produce name#discrim anyway, so this is just a less concise way of doing that

2021-04-18 15:11 UTC, Akarys42 commented on bot/exts/moderation/logs.py
> +            f"edited a message in #{after.channel}.",
Mentions don't actually render in embed titles, that's why I used this.

2021-04-18 15:12 UTC, vcokltfre commented on bot/exts/moderation/logs.py
> +            f"edited a message in #{after.channel}.",
Ah yep, you're right my bad

2021-04-18 15:23 UTC, vcokltfre approved these changes
LGTM! :shipit:

2021-04-18 16:02 UTC, codephile1221 requested changes
Thank you for PR :star: !
I don't have much to comment on.

2021-04-18 16:02 UTC, codephile1221 commented on bot/exts/moderation/logs.py
> +        await self.post_formatted_message(self.bot.user, "logged in!")
Yeet the lines in `bot.py`, that is.

2021-04-18 16:05 UTC, gustavwilliam commented
You guys are awesome for reviewing this @codephile1221 and @vcokltfre! Also, I’m curious if any of you tested the PR as well, so we know it works in production?

2021-04-18 16:27 UTC, vcokltfre commented
![image](https://user-images.githubusercontent.com/16879430/115152941-513f9b80-a06b-11eb-9f2b-680417f7ea85.png)
Having done this: for consistency the dm log should also have the timestamp and avatar

2021-04-18 17:46 UTC, Akarys42 commented on bot/constants.py
> +    dm_log = int(os.getenv("CHANNEL_LOGS", 833345326675918900))
It was a way to make it easier for development as you'd only have one env var to define

2021-04-18 17:46 UTC, Akarys42 commented on bot/exts/moderation/logs.py
> +        await self.post_formatted_message(self.bot.user, "logged in!")
I think it is fine to have both, #logs is mod only

2021-04-18 17:52 UTC, gustavwilliam commented on bot/exts/moderation/logs.py
> +        await self.post_formatted_message(self.bot.user, "logged in!")
Do we even want this in the mod log? Isn’t it enough in bot commands?

2021-04-18 18:14 UTC, codephile1221 commented on bot/exts/moderation/logs.py
> +        await self.post_formatted_message(self.bot.user, "logged in!")
@gustavwilliam , did you mean `#dev-logs` ?
I feel logging it once is enough too.

2021-04-18 18:23 UTC, codephile1221 commented on bot/constants.py
> +    dm_log = int(os.getenv("CHANNEL_LOGS", 833345326675918900))
Alright.

2021-04-18 18:46 UTC, Akarys42 commented on bot/exts/moderation/logs.py
> +            if not self.log_channel:
I like how it is like that :P

2021-04-18 18:57 UTC, codephile1221 commented on bot/exts/moderation/logs.py
> +            if not self.log_channel:
Okay 👍 .

2021-04-18 18:59 UTC, codephile1221 approved these changes
Looks good to me! 

🚢 it.

2021-04-18 19:00 UTC, gustavwilliam commented
I'll count this as two approvals. @Akarys42 ready to merge?

2021-04-19 03:38 UTC, codephile1221 reviewed
Forgot to mention about updating `.env-example`.

2021-04-19 09:13 UTC, merged