Mod toolkit, the forgotten stage: DM command
gurkult/gurkbot pull request #119
Opened 2021-04-20 16:01 UTC by Akarys42

*I may or may not have forgotten about this command during the last PR*

This PR adds a DM command reserved for moderators and SC members. It also fixes a major bug causing the error handler to just not work.

2021-04-20 16:44 UTC, gustavwilliam requested changes
Thanks for the fast PR! I just have a few minor comments.

2021-04-20 16:44 UTC, gustavwilliam commented on bot/exts/moderation/mod_utils.py
> +    """Cog used for various utility moderation commands."""
```suggestion
    """Cog used for various moderation utility commands."""
```
I feel like this sounds better.

2021-04-20 16:44 UTC, gustavwilliam commented on bot/exts/moderation/mod_utils.py
> +        except Forbidden:
Should we log this as well, so we have a record of the fact that the DM arrived or didn't arrive?

2021-04-20 16:44 UTC, gustavwilliam commented on bot/exts/moderation/mod_utils.py
> +    """Load the moderation log during setup."""
```suggestion
    """Load the moderation utils cog during setup."""
```
Something like this?

2021-04-20 17:09 UTC, Akarys42 commented on bot/exts/moderation/mod_utils.py
> +        except Forbidden:
We do get a reaction on the message depending on whenever it failed or not

2021-04-23 15:32 UTC, gustavwilliam approved these changes
LGTM! (Code review only)

2021-04-23 15:32 UTC, gustavwilliam commented on bot/exts/backend/error_handler.py
> +        await dev_alerts.send(embed=push_alert)
Good thinking!

2021-04-24 09:56 UTC, codephile1221 requested changes
Looks good :+1: .

2021-04-24 09:56 UTC, codephile1221 commented on bot/exts/moderation/logs.py
> +    return cog.post_message
What's this for? I don't see it used anywhere.

2021-04-24 11:19 UTC, Akarys42 commented on bot/exts/moderation/logs.py
> +    return cog.post_message
Right now it isn't but I want it to be part of the public API of this cog, I bet it will be used in the future

2021-04-24 11:26 UTC, codephile1221 approved these changes
Looks good to me!
⭐

2021-04-24 11:26 UTC, codephile1221 commented on bot/exts/moderation/logs.py
> +    return cog.post_message
Good call.

2021-04-24 11:46 UTC, merged