chore: set poetry up for project
gurkult/gurkbot pull request #129
Opened 2021-06-19 01:04 UTC by DudeBro249

- Set [poetry](https://python-poetry.org/) up for this project, using `pyproject.toml` and `poetry.toml`
- Add tasks for linting, formatting, and installing git hooks
- Edited both `.pre-commit-config.yaml` and `.github/workflows/linting.yml` to use poetry instead of pipenv
- Added instructions for local development with poetry in `README.md`
- Removed pipenv from project

2021-06-21 09:28 UTC, Arnav-2004 requested changes
Hi, just a few changes.

2021-06-21 09:28 UTC, Arnav-2004 commented on README.md
> +`poetry run bot` - Runs the discord bot. You can also do this with the more recommended `docker-compose up`
```suggestion
`poetry run bot` - Runs the discord bot.
```
It would be better if we had a different section for docker setup.

2021-06-21 09:28 UTC, Arnav-2004 commented on bot/__main__.py
> +def main() -> None:
I don't think a function for this task is necessary.

2021-06-21 10:16 UTC, RohanJnr commented on README.md
> +`poetry run bot` - Runs the discord bot. You can also do this with the more recommended `docker-compose up`
I will make changes to the readme in a later PR, we want to enforce docker over manual run.

2021-06-21 16:57 UTC, AyushLikesMoney commented on README.md
> +`poetry run bot` - Runs the discord bot. You can also do this with the more recommended `docker-compose up`
Cool, I'll remove the `docker-compose up` part then

2021-06-21 16:59 UTC, DudeBro249 commented on README.md
> +`poetry run bot` - Runs the discord bot. You can also do this with the more recommended `docker-compose up`
Cool, I'll remove the `docker-compose up` part then.

2021-06-21 17:00 UTC, DudeBro249 commented on bot/__main__.py
> +def main() -> None:
@Arnav-2004 a function is necessary for poetry scripts - https://github.com/DudeBro249/gurkbot/blob/chore/poetry-setup/pyproject.toml#L38

2021-06-21 17:03 UTC, Arnav-2004 commented on bot/__main__.py
> +def main() -> None:
ah, looks good then

2021-06-21 17:06 UTC, DudeBro249 commented on README.md
> +`poetry run bot` - Runs the discord bot. You can also do this with the more recommended `docker-compose up`
Done

2021-06-22 13:49 UTC, RohanJnr commented on .github/workflows/linting.yml
> +          poetry install
would this create a virtual env? if yes, then we should install to system instead.
https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker
The first answer has some good content.

2021-06-22 20:20 UTC, DudeBro249 commented on .github/workflows/linting.yml
> +          poetry install
Done

2021-06-24 04:59 UTC, Arnav-2004 commented on bot/utils/environment.py
> +        )
Can you explain what this does?

2021-06-24 06:03 UTC, DudeBro249 commented on bot/utils/environment.py
> +        )
Might remove [`bot/utils/environment.py`](https://github.com/DudeBro249/gurkbot/blob/chore/poetry-setup/bot/utils/environment.py) based on the suggestions of @RohanJnr

2021-06-24 06:04 UTC, DudeBro249 commented on bot/utils/environment.py
> +        )
But that part essentially means that you cannot have a default value for an environment variable and have the environment  variable be required from the environment at the same time @Arnav-2004

2021-06-24 06:05 UTC, Arnav-2004 commented on bot/utils/environment.py
> +        )
oh alright

2021-06-26 03:36 UTC, DudeBro249 commented on bot/utils/environment.py
> +        )
I've removed the file

2021-06-26 07:04 UTC, RohanJnr approved these changes

2021-06-26 07:11 UTC, Arnav-2004 approved these changes
Looks good to me!

2021-06-26 09:22 UTC, Akarys42 requested changes
Thanks a lot for the PR! I have a few things to add

2021-06-26 09:22 UTC, Akarys42 commented on .dockerignore
> +# Byte-compiled / optimized / DLL files
If we really want to add a docker ignore we should really add `.git`, as it is the largest file by large in the repo

2021-06-26 09:22 UTC, Akarys42 commented on .github/workflows/linting.yml
> -      PIPENV_CACHE_DIR: /tmp/pip-cache-dir
This should be replaced by `POETRY_CACHE_DIR` with the same value

2021-06-26 09:22 UTC, Akarys42 commented on Dockerfile
> -ENV PIP_NO_CACHE_DIR=false \
`PIP_NO_CACHE_DIR` should stay

2021-06-26 09:22 UTC, Akarys42 commented on Dockerfile
> +RUN poetry config virtualenvs.create false
Let's put those two `RUN` instructions in one using `&&` in between them to remove a cache layer

2021-06-26 09:22 UTC, Akarys42 commented on Dockerfile
> +CMD ["-m" , "bot"]
Those should be set before the whole poetry deal to optimize caching, like it was previously

2021-06-26 09:22 UTC, Akarys42 commented on README.md
> +   poetry run bot
I believe it is a custom task? 
```suggestion
   poetry run task bot
```

2021-06-26 09:22 UTC, Akarys42 commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
lol, that should be changed 
```suggestion
authors = ["The Gurkult Community <noreply@gurkult.com>"]
```

2021-06-26 14:31 UTC, DudeBro249 commented on README.md
> +   poetry run bot
Oh I'm sorry I replaced it in one place and not the other, I'll make this change, thanks for catching it!

2021-06-26 14:31 UTC, DudeBro249 commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Awesome, will do that

2021-06-26 14:32 UTC, DudeBro249 commented on Dockerfile
> -ENV PIP_NO_CACHE_DIR=false \
Got it

2021-06-26 14:33 UTC, DudeBro249 commented on .github/workflows/linting.yml
> -      PIPENV_CACHE_DIR: /tmp/pip-cache-dir
Aah I didn't actually know what this did, should've researched more

2021-06-26 14:36 UTC, DudeBro249 commented on Dockerfile
> +CMD ["-m" , "bot"]
Alright

2021-06-26 14:37 UTC, DudeBro249 commented on .dockerignore
> +# Byte-compiled / optimized / DLL files
@Akarys42 Aah got it - may have to remove one day _**if**_ we install a python package from a remote git repository provider. However, I will remove it for now as it seems that this is not the case, and _probably_ will not be.

2021-06-26 14:37 UTC, DudeBro249 commented on .github/workflows/linting.yml
> -      PIPENV_CACHE_DIR: /tmp/pip-cache-dir
Will replace

2021-06-26 14:41 UTC, DudeBro249 commented on .dockerignore
> +# Byte-compiled / optimized / DLL files
Got it

2021-06-26 14:42 UTC, DudeBro249 commented on .github/workflows/linting.yml
> -      PIPENV_CACHE_DIR: /tmp/pip-cache-dir
Done

2021-06-26 14:42 UTC, DudeBro249 commented on .dockerignore
> +# Byte-compiled / optimized / DLL files
Done

2021-06-26 14:43 UTC, DudeBro249 commented on Dockerfile
> -ENV PIP_NO_CACHE_DIR=false \
Done

2021-06-26 14:44 UTC, DudeBro249 commented on Dockerfile
> +RUN poetry config virtualenvs.create false
Done

2021-06-26 14:45 UTC, DudeBro249 commented on Dockerfile
> +CMD ["-m" , "bot"]
Done

2021-06-26 14:45 UTC, DudeBro249 commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Done

2021-06-26 14:45 UTC, DudeBro249 commented on README.md
> +   poetry run bot
Done

2021-06-27 08:43 UTC, Akarys42 approved these changes
Thanks a bunch! :shipit:

2021-06-27 08:45 UTC, merged