[Feature] Gurkify
gurkult/gurkbot pull request #131
Opened 2021-06-22 17:36 UTC by Arnav-2004

2021-06-23 10:17 UTC, JacobMonck approved these changes
Looks good to me.

2021-06-27 16:02 UTC, DudeBro249 approved these changes
Looking good 😎!

2021-09-19 18:07 UTC, RohanJnr requested changes

2021-09-19 18:07 UTC, RohanJnr commented on bot/exts/gurkan/gurkify.py
> +        """Gurkifying users display name."""
```suggestion
        """Gurkify user's display name."""
```

2021-09-19 18:07 UTC, RohanJnr commented on bot/exts/gurkan/gurkify.py
> +            return
```suggestion
            return
```
```suggestion
```

2021-12-17 02:25 UTC, gustavwilliam commented
@Arnav-2004 I did some error handling on this, so we might get it merged soon. Some refactoring would be nice for the error embeds. I might do it now.

2021-12-17 02:41 UTC, gustavwilliam approved these changes
Let's try it out

2021-12-17 02:43 UTC, merged