[FEAT] bot stats
gurkult/gurkbot pull request #133
Opened 2021-06-24 12:03 UTC by Arnav-2004

This pr will close #132

Added `!ping` and `!stats` command.

`!stats` includes python version, d.py version and uptime of the bot.

2021-06-27 15:57 UTC, DudeBro249 requested changes
PR looks good - I've left one comment. Other than that, just migrate to poetry whenever possible(by merging latest changes from the main branch and adding `humanize` as a dependency), and then I think this PR will be good to go!

2021-06-27 15:57 UTC, DudeBro249 commented on bot/exts/utils/bot_stats.py
> +        fields = [
Can we use a dictionary here instead of a list of tuples?(Each key would be the name of the field, and the value would be the value of the field)

2021-06-27 17:30 UTC, Arnav-2004 commented on bot/exts/utils/bot_stats.py
> +        fields = [
Done!

2021-06-27 17:32 UTC, DudeBro249 approved these changes
Looks great!

2021-07-28 13:24 UTC, vivax3794 approved these changes
lgtm

2021-08-07 19:28 UTC, merged