Create PR on Gurkcraft command
gurkult/gurkbot pull request #139
Opened 2021-08-21 10:25 UTC by aphkyle

Leaving a random comment

2021-08-22 06:03 UTC, gustavwilliam requested changes
I'm so excited for this command! Thanks for making it 😄

Most of my suggestions are to make the code fit out codebase better and make things more modular. Test things out, since I haven't tested this, and feel free to disagree with my comments. They're mostly suggestions.

2021-08-22 06:18 UTC, aphkyle commented on bot/exts/gurkcraft/gurkcraft.py
> +    async def mcstatus(self, ctx: discord.Context) -> NoReturn:
`NoReturn` is to specify if a function doesn't return anything. `None` means it will returns None

2021-08-22 06:19 UTC, aphkyle commented on bot/exts/gurkcraft/gurkcraft.py
> +    async def mcstatus(self, ctx: discord.Context) -> NoReturn:
Sure.

2021-08-22 06:22 UTC, zeeshanok commented on bot/exts/gurkcraft/gurkcraft.py
> +    async def mcstatus(self, ctx: discord.Context) -> NoReturn:
`NoReturn` actually means the function will never terminate or always throws an error, ie. it *never* returns normally.

2021-08-22 06:31 UTC, aphkyle commented on bot/exts/gurkcraft/gurkcraft.py
> +        status = self.server.status()
This will fetch every time command runs.

2021-08-22 06:48 UTC, aphkyle commented
Seems like I fixed the issues. Try to find more. I'd be happy to fix them.

2021-08-22 06:48 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +        status = self.server.status()
Excellent 👍

2021-08-22 07:01 UTC, gustavwilliam requested changes
Alrighty, this is starting to look good! These comments should be some of my very last here—hopefully my very last before approving this. Good work 😄

2021-08-22 07:01 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +        embed_value = f"""\
Instead of one huge string for all of this, you could use multiple "fields", where the field header is the "key" of the row and the value is the content. Check out how we did this with the `!bot_stats` command.

I'm fine wither way, but would probably prefer fields to keep things consistent.

2021-08-22 07:01 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +def setup(bot: Bot) -> NoReturn:
```suggestion
def setup(bot: Bot) -> None:
```

2021-08-22 07:59 UTC, RohanJnr commented
is it possible to have the number of players online included in the channel topic? maybe pull the data every 1-2min

2021-08-22 08:01 UTC, RohanJnr commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.server = MinecraftServer("129.159.251.229", 25565)
lets have the server IP as a environment variable

2021-08-22 09:40 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.server = MinecraftServer("129.159.251.229", 25565)
I would rather have it default to `mc.gurkult.com` with a potential override using an env var

2021-08-23 11:01 UTC, aphkyle commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.server = MinecraftServer("129.159.251.229", 25565)
Can I not save this in `constants.py` and just leave `mc.gurkult.com` there?

2021-08-24 14:10 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.server = MinecraftServer("129.159.251.229", 25565)
I'd personally be fine with just having `mc.gurkult.com` in `constants.py`. If we want to allow for a custom IP, we could add that later.

What do you think @Akarys42 @RohanJnr?

2021-08-24 14:13 UTC, gustavwilliam commented
> is it possible to have the number of players online included in the channel topic? maybe pull the data every 1-2min

@RohanJnr I like the idea. The wait time between updates would probably need to be longer, due to rate limits, but it would still be cool.

Can you open a separate issue (or PR?) where we can discuss this?

2021-08-24 14:35 UTC, RohanJnr commented
> > is it possible to have the number of players online included in the channel topic? maybe pull the data every 1-2min
> 
> @RohanJnr I like the idea. The wait time between updates would probably need to be longer, due to rate limits, but it would still be cool.
> 
> Can you open a separate issue (or PR?) where we can discuss this?

I think this will prolly not need another PR, we can accomplish it within this, what do you say?

2021-08-24 14:56 UTC, gustavwilliam commented
I'm all for small and quick reviews, rather than massive ones. I'd like to just get this merged now, and we can quickly write the other functionality afterwards.

2021-08-24 15:24 UTC, gustavwilliam approved these changes
Alright, LGTM! Feel free to address the suggestion I left, but I don't see a reason for me to do another review :)

2021-08-24 15:24 UTC, gustavwilliam commented on bot/constants.py
> +MC_SERVER_ADDRESS = "mc.gurkult.com"
```suggestion
class Minecraft(NamedTuple):
    server_address = "mc.gurkult.com"
```
I think making this a NamedTuple, like the rest of the constants, would be nice. The command above could also be removed if you do this.

(Just remember to change the references to the address if you do this.)

2021-08-24 15:35 UTC, RohanJnr commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.server = MinecraftServer("129.159.251.229", 25565)
that still exposes the server address, I would still press upon having it hidden

2021-08-30 20:43 UTC, merged