Gurkcraft: automatically update channel topic
gurkult/gurkbot pull request #141
Opened 2021-09-03 09:41 UTC by Akarys42

Update the topic of the `#gurkcraft` channel to give some information about the status of the server. Here is an example:

![Screenshot_20210903_113511](https://user-images.githubusercontent.com/44778521/131985191-359c444f-a1a0-487e-a90b-835b9e4fca47.png)

It also makes `!mcstatus` gracefully handle `OSError`s.

2021-09-03 15:12 UTC, gustavwilliam requested changes
Thanks, dear Matteo von Akarys. This looks mostly greasy, but I have a few suggestions. Feel free to dispute them where it seems reasonable.

2021-09-03 15:12 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +            await ctx.send("The server is currently offline.")
Could you send this in a red error embed? That would be more consistent with the rest of the gurkbot style

2021-09-03 15:12 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +    @tasks.loop(minutes=2)
Even if this might be fine, I'm scared that discord might get annoyed by getting 720 channel update events per day.

What do you think of increasing it to 3 or 5 minutes? It's still be a lot, but it's not as bad.

2021-09-03 15:12 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +            players = [user["name"] for user in status.raw["players"]["sample"]]
What do you think about making this more DRY and creating an `extract_users` function, or something like that.

And maybe combine this with the next few lines to handle the exceptions? Might work.

2021-09-03 15:12 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +                + f"Last server latency: {status.latency}ms"
```suggestion
                + f"Last server latency: {status.latency}ms"
```
I think we should just access the latency through the `!mcstatus` command. The latency makes the description a bit cluttered imo.

2021-09-03 15:12 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +            topic=f"Our gurkan Minecraft server. Join: {Minecraft.server_address} ! \n{description}"
```suggestion
            topic=f"Our gurkan Minecraft server. Join: {Minecraft.server_address}!\n{description}"
```
Assuming the "!" and " " don't serve any real function, other than looking nice, I think we should remove 'em. We could possibly get rid of the "!" if you think that would make things easier to parse (for the human eye).

2021-09-03 15:43 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +        self.gurkcraft: Optional[TextChannel] = None
Yep, the cache is empty, so it simply won't work.

2021-09-03 15:45 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +            topic=f"Our gurkan Minecraft server. Join: {Minecraft.server_address} ! \n{description}"
The space is important since the line break won't be shown on the main channel view, at the top. Otherwise, there would be no break between the two sentences, making it hard to read. We could replace it with a simple dot, but I personally like exclamation marks :P don't mind either way though.

2021-09-03 20:45 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +            topic=f"Our gurkan Minecraft server. Join: {Minecraft.server_address} ! \n{description}"
Sounds good. Feel free to do this however you want then :) 👍

2021-09-05 17:37 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +            await ctx.send("The server is currently offline.")
Solved in 864cf63

2021-09-05 17:37 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +    @tasks.loop(minutes=2)
Changed to 5 minutes in be11119

2021-09-05 17:56 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +            players = [user["name"] for user in status.raw["players"]["sample"]]
Done in e0862f7

2021-09-05 17:57 UTC, Akarys42 commented on bot/exts/gurkcraft/gurkcraft.py
> +                + f"Last server latency: {status.latency}ms"
Done in cde8b77

2021-09-07 05:58 UTC, gustavwilliam approved these changes
Looks excellent! Well done.

I'm gonna merge this, hope you've done some testing and do the final testing in production.

2021-09-07 05:58 UTC, gustavwilliam commented on bot/exts/gurkcraft/gurkcraft.py
> +        """Collect informations about the server and update the description of the channel."""
```suggestion
        """Collect information about the server and update the description of the channel."""
```
Just some picky grammar

2021-09-07 05:58 UTC, merged