use allowed mentions to prevent mentioning everyone
gurkult/gurkbot pull request #158
Opened 2021-12-15 10:24 UTC by onerandomusername

closes GH-39

2021-12-25 15:57 UTC, gustavwilliam requested changes
Pure code review. Just one comment, but otherwise LGTM!

2021-12-25 15:57 UTC, gustavwilliam commented on bot/bot.py
> +                roles=roles,
```suggestion
        allowed_roles = [
            Object(r)
            for r in [
                constants.Roles.steering_council,
                constants.Roles.moderators,
                constants.Roles.gurkult_lords,
            ]
        ]

        super().__init__(
            command_prefix=constants.PREFIX,
            intents=intents,
            allowed_mentions=AllowedMentions(
                everyone=None,
                users=True,
                roles=allowed_roles,
```
Let's make it explicit.

2021-12-26 09:40 UTC, gustavwilliam approved these changes
LGTM, code review-wise.

2021-12-28 08:07 UTC, onerandomusername commented on bot/bot.py
> +                roles=roles,
https://github.com/gurkult/gurkbot/pull/158/commits/13db234f55c490ec54c38a658c1dd06f9dbec158

2021-12-29 07:24 UTC, Akarys42 approved these changes

2021-12-29 07:24 UTC, merged