update ot name more often
gurkult/gurkbot pull request #161
Opened 2021-12-16 07:17 UTC by onerandomusername

### NOTE:
this depends on GH-155 as that brings the bot to discord.py 2.0, which is where the time param for task.loop was added.

### Relevent Issues

Closes GH-126

### Description
updates the offtopic channel name every 12 hours instead of 24.

Of the first two commits, the first one rewrote the task to use discord.py tasks, and the second one added the 12 hour interval.

2022-01-05 23:22 UTC, onerandomusername commented
I'll rebase this shortly, solve conflicts,  and fix the embed referencing the name of the day when it's actually the name of 12 hours.

2022-01-13 18:41 UTC, codephile1221 requested changes
I have not tested locally *as of yet*.

2022-01-13 18:41 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +            new_name = random.choice(chosen_ot_names)
Reading this made me confused at first because I saw `new_name == current_name` and then `while new_name == current_name` immediately after.

Why not just use remove method on `chosen_ot_names`, and then pass it to `choice` method? (yes, I know you're just adapting the old code.)

Something like:
```
if current_name in chosen_ot_names:
    chosen_ot_names.remove()
```

Actually, thinking about it, you could do a set comprehension on line 206 (instead of a list comprehension) and use `discard` method to remove `current_name`.

2022-01-13 18:41 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +            self.ot_channel, f"{new_name}", True, "New Off-Topic Name!"
```suggestion
            self.ot_channel, new_name, True, "New Off-Topic Name!"
```

2022-01-14 06:52 UTC, codephile1221 approved these changes
Looks good to me :star: .

2022-01-15 06:54 UTC, codephile1221 requested changes

2022-01-15 06:54 UTC, codephile1221 commented on bot/exts/fun/off_topic.py
> +        new_name = random.choice(list(chosen_ot_names))
```suggestion
        new_name = random.choice(tuple(chosen_ot_names))
```
This might end up being a nitpick, but since you don't need to modify the list anywhere, why not just use a tuple? There

2022-01-15 15:57 UTC, codephile1221 approved these changes
lgtm!

2022-02-03 05:07 UTC, RohanJnr requested changes

2022-02-03 05:07 UTC, RohanJnr commented on bot/exts/fun/off_topic.py
> +        new_name = random.choice(tuple(chosen_ot_names))
Sometimes, the set `chosen_ot_names` might turn out to be an empty set with this error:
```
gurkbot  | Unhandled exception in internal background task 'update_ot_channel_name'.
gurkbot  | Traceback (most recent call last):
gurkbot  |   File "/usr/local/lib/python3.9/site-packages/disnake/ext/tasks/__init__.py", line 167, in _loop
gurkbot  |     await self.coro(*args, **kwargs)
gurkbot  |   File "/bot/bot/exts/fun/off_topic.py", line 224, in update_ot_channel_name
gurkbot  |     new_name = random.choice(tuple(chosen_ot_names))
gurkbot  |   File "/usr/local/lib/python3.9/random.py", line 346, in choice
gurkbot  |     return seq[self._randbelow(len(seq))]
gurkbot  | IndexError: tuple index out of range
```
This is mostly due to low number of off topic names but we should handle this situation.

2022-02-03 05:08 UTC, RohanJnr commented
Do we want to change these reactions to buttons?
![image](https://user-images.githubusercontent.com/37217450/152284668-1cfb9bf9-e8c3-41b7-a1d6-99a42bdf4363.png)

2022-10-25 09:40 UTC, vivekashok1221 commented
I appreciate the work you have put in to this PR but we have decided that this issue is not relevant anymore. Thank you.

2022-10-25 09:40 UTC, closed without merging