feat: add test guild configuration for application commands
gurkult/gurkbot pull request #167
Opened 2022-01-08 07:34 UTC by onerandomusername

Adds a test guild configuration with an environment variable.

Without this option, commands register globally which means up to an hour of waiting for commands to be registered and appear in the test guild.

2022-01-17 13:50 UTC, Arnav-2004 requested changes

2022-01-17 13:50 UTC, Arnav-2004 commented on .env-example
> +TEST_GUILDS=
Can we have a placeholder here for how to actually use this. `TEST_GUILDS="guild_id1,guild_id2"`

2022-01-17 14:42 UTC, codephile1221 requested changes

2022-01-17 14:42 UTC, codephile1221 commented on bot/constants.py
> +    TEST_GUILDS = [int(x.strip()) for x in TEST_GUILDS.split(",")]
```suggestion
    TEST_GUILDS = [int(x) for x in TEST_GUILDS.split(",")]
```
This will suffice since `int()` strips whitespace.

2022-01-17 14:53 UTC, onerandomusername commented on bot/constants.py
> +    TEST_GUILDS = [int(x.strip()) for x in TEST_GUILDS.split(",")]
https://github.com/gurkult/gurkbot/pull/167/commits/d381cbdf863fa9b0ce718450d33554f664d98ba1

2022-01-17 14:53 UTC, onerandomusername commented on .env-example
> +TEST_GUILDS=
https://github.com/gurkult/gurkbot/pull/167/commits/90ba961c3a2dfe26ef048ad3d2ced80adb7d7d32

2022-01-17 14:57 UTC, Arnav-2004 approved these changes
Looks good to me!

2022-01-17 15:12 UTC, codephile1221 approved these changes
LGTM.

2022-01-18 07:16 UTC, gustavwilliam requested changes
A few questions and comments.

2022-01-18 07:16 UTC, gustavwilliam commented on .env-example
> +# eg: TEST_GUILDS="789192517375623228, 793864455527202847"
```suggestion
# Example: TEST_GUILDS=789192517375623228,793864455527202847
```
Doesn't this work too?

2022-01-18 07:16 UTC, gustavwilliam commented on .env-example
> +# this is required if you do not want to wait up to an hour for commands to sync
```suggestion
# This is required if you do not want to wait up to an hour for commands to sync
```

2022-01-18 07:16 UTC, gustavwilliam commented on bot/bot.py
> +        test_guilds = None
Shouldn't this use `Embed.Empty` instead of `None`?

2022-01-18 07:16 UTC, gustavwilliam commented on bot/bot.py
> +            logger.warning("Loading with test guilds.")
Why is this logging a warning, and not just info?

I guess it makes sense to send a warning if test guilds are active in production, but if you're debugging, a warning here makes no sense IMO.

2022-01-18 07:25 UTC, codephile1221 commented on bot/bot.py
> +        test_guilds = None
What does `test_guilds` have to do with embeds? `test_guilds` parameter accepts list of `int`s or `None`.

2022-01-18 08:42 UTC, gustavwilliam commented on bot/bot.py
> +        test_guilds = None
Lol true.

2022-01-18 12:45 UTC, onerandomusername commented on bot/bot.py
> +            logger.warning("Loading with test guilds.")
It makes sense to send a warning in prod, so I think its fine here.

2022-01-18 13:43 UTC, gustavwilliam approved these changes
:shipit:

2022-01-18 13:44 UTC, merged