Update readme to include docker setup
gurkult/gurkbot pull request #174
Opened 2022-01-19 20:09 UTC by RohanJnr

2022-01-19 20:16 UTC, onerandomusername requested changes
Pretty good, a few things about the .env set up, but other than that...

2022-01-19 20:16 UTC, onerandomusername commented on README.md
> +Create a `.env` file with following contents:
Please include `TEST_GUILDS`, its extremely important to be set.

This variable can take a list of guild ids, and when set, will register application commands to that guild. This is recommended for testing, as it may take an hour for commands to register otherwise.

We also have this file as well:
https://github.com/gurkult/gurkbot/blob/main/.env-example

2022-01-21 10:19 UTC, gustavwilliam requested changes
Nice! Just a few comments.

Also, could you mention somewhere that postgres needs to be up and running? Feel free to link to whatever documentation page explains steps of setting things up, but at least mention that they need it set up and make sure they have a way to figure out how to set it up.

2022-01-21 10:19 UTC, gustavwilliam commented on README.md
>     ```text
What do you think about just linking to `.env-example` instead? So we don't have to maintain the environment variables in two places.

2022-01-21 10:19 UTC, gustavwilliam commented on README.md
> +2. Install docker-compose: `pip install docker-compose`
Could you link to the docker-compose installation instructions instead? It should mention all requirements etc., so we don't put the maintainable burden of keeping this updated to us.

2022-01-21 10:19 UTC, gustavwilliam commented on README.md
> +1. Add `DATABASE_URL` variable to `.env` file.
Could you specify how one gets this variable?

2022-01-24 09:17 UTC, gustavwilliam requested changes
One final comment!

2022-02-05 14:55 UTC, gustavwilliam approved these changes
LGMT! Thanks a lot

2022-02-05 14:58 UTC, merged