Port internal eval command
gurkult/gurkbot pull request #177
Opened 2022-01-28 09:49 UTC by Akarys42

This is a port of the internal eval command of the Python Discord bot (https://github.com/python-discord/bot/blob/main/bot/exts/utils/internal.py).
The command is locked to the DevOps and Steering Council roles.

2022-01-28 15:31 UTC, ShakyaMajumdar commented
Looks good to me

2022-01-28 15:31 UTC, ShakyaMajumdar approved these changes
Looks good to me

2022-01-28 18:28 UTC, vivekashok1221 approved these changes
lgtm.

2022-01-30 00:51 UTC, gustavwilliam commented on bot/constants.py
> +    devops = int(os.getenv("ROLE_DEVOPS", 918880926606430308))
Should we update sm the env example with this role while we're at it?

2022-01-30 00:51 UTC, gustavwilliam commented on bot/exts/utils/devops.py
> +    async def eval(self, ctx: Context, *, code: str) -> None:
Has anyone tested the permissions? Cc @Akarys42 @vivekashok1221 @ShakyaMajumdar

I can't test it now, but if you've already tested it, it might not do it myself.

2022-01-30 00:51 UTC, gustavwilliam commented on bot/exts/utils/devops.py
> +    @group(name="devops")
So `!devops eval` will be the command name?

2022-01-30 04:26 UTC, onerandomusername commented on bot/exts/utils/devops.py
> +    async def eval(self, ctx: Context, *, code: str) -> None:
i'll check tomorrow

2022-01-30 04:27 UTC, onerandomusername requested changes
leaving requesting changes review so I'm able to review before a merge

2022-02-11 20:00 UTC, gustavwilliam commented on bot/exts/utils/devops.py
> +    async def eval(self, ctx: Context, *, code: str) -> None:
Have tested. Seems right.

2022-02-11 20:04 UTC, gustavwilliam approved these changes
LGTM

2022-02-11 20:07 UTC, merged