Eval
gurkult/gurkbot pull request #26
Opened 2020-12-22 09:19 UTC by Shivansh-007

Closing #24

2020-12-22 12:11 UTC, codephile1221 commented
It'd be nice if the bot sends a user friendly message if any of the required argument like ```language``` is missing. Currently, I do not see any such provisions.

2020-12-22 18:17 UTC, gustavwilliam requested changes
Thanks for the PR! I haven't tested the feature yet, so this is purely a code review.

Generally, my main issue with this code would be how many things happen inside the eval function. I'd love to see this broken out into smaller helper methods. This quote sums things up nicely:
> Every function should do only one thing, and do that really well.

At the end of the day, this seems like a great start 😄

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                code.pop(i)  # remove following whitespace character
```suggestion
                code.pop(i)  # Remove following whitespace character
```
Capitalize.

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +        text = None
Most of this could go in a helper method. That would be cleaner.

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                    return await ctx.send("File must be smaller than 20 kio.")
```suggestion
                    await ctx.send("File must be smaller than 20 kio.")
                    return
```
I generally like doing it like this, but both ways are probably fine.

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                base_url = urllib.parse.quote_plus(code.split(' ')[-1][5:].strip('/'), safe=';/?:@&=$,><-[]')
Mention the fact that only certain pastebin links will be accepted. A comment would be enough.

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                'sh': 'bash',
We already have this mapping in resources?

2020-12-22 18:17 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
I would prefer to send this as an embed.

2020-12-23 02:46 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +                'sh': 'bash',
This does what you have asked to do here:
https://github.com/gurkult/gurkbot/pull/26#discussion_r547416077

2020-12-23 02:47 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                'sh': 'bash',
It would be nice to have that in the config file. Having it in multiple files is quite annoying and is prone to bugs.

2020-12-23 02:48 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
Hmmm, I like the current one, here is a screenshot:
![Screenshot from 2020-12-23 08-17-12](https://user-images.githubusercontent.com/69356296/102953477-64948d00-44f7-11eb-9260-a88c93b2eb4b.png)
![Screenshot from 2020-12-23 08-17-23](https://user-images.githubusercontent.com/69356296/102953480-65c5ba00-44f7-11eb-912c-c680f2fe491e.png)

2020-12-23 02:50 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
I don’t mind the formatting itself. The issue to me is that you’re sending user generated text as a message. I don’t like doing that. We should basically never to that, outside of an embed. Embeds are safe and won’t, for example, ping everyone.

We can discuss this further in #24 if you want to.

2020-12-23 02:55 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
Alright will do that, also will it be pinging the user?

2020-12-23 02:55 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +                'sh': 'bash',
Hmmm will do that!

2020-12-23 02:56 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
That could be nice, for busy channels.

2020-12-23 03:04 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
If it pings, what is the need of the embed, from above i think you only wanted it  so that it doesn't ping wrong users, and in a embed it won't  ping.

2020-12-23 03:06 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            await ctx.send(f'{ctx.author.mention} {icon} {msg}.\n\n```{lang}\n{result}```')
The ping would ping the author. That can’t go wrong. The issue I’m talking about has to do with text that the user can influence, by for example printing things.

2020-12-23 08:42 UTC, codephile1221 commented on bot/exts/utils/eval.py
> +                return await ctx.send("Missing Required Argument Code.")
Shouldn't this be in the error handler?
You already have provisions for handling MissingRequiredArgument in [eval_command_error](https://github.com/gurkult/gurkbot/pull/26/files#diff-149dab52cd4b95066ca43ace56a6b814245c3eb943f35259fb3b6275807b5b13R277-R285)

2020-12-23 09:17 UTC, Shivansh-007 commented on bot/exts/utils/eval.py
> +                return await ctx.send("Missing Required Argument Code.")
![image](https://user-images.githubusercontent.com/69356296/102980481-a5a79400-452d-11eb-8071-b820cb44a2a4.png)
This how it currently is , so I don't see what changes are requied

2020-12-25 23:53 UTC, gustavwilliam requested changes
From my last testing, this worked like charm. I like it.

The requested changes in this file are mostly about refactoring the code and using helper methods, instead of having one huge method that does everything. If there's something that I forgot to mention, that would fit in a helper method, feel free to create a helper method for it.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +}
Preferably put these in a resource file, in the eval resources directory.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            in a new hastebin and the link will be returned.
Update this to match the current configuration. Also, mention that the output will be truncated and that a link will be posted. Right now, they don't know that a truncated version will be returned.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +        text = None
It would be nice to have all of this in a helper method. Something like `_parse` (a method of the `Eval` class) could work for it. Keeping all of the code one function like this makes it quite hard to debug.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +        async with ctx.typing():
Start typing at the beginning of the command. The very beginning. Maybe the parsing takes some time for longer inputs? It's nice to get feedback immediately.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                text = buffer.read().decode("utf-8")
Turn this into a helper method as well. Something like `_code_from_attachments` should be good.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                        text = await response.text()
Turn this into a helper method, like `_code_from_url`.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +                return
It would be nice to see this in a helper method as well.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            if len(result) > 1991 or result.count("\n") > 40:
The newline limit isn't 40. Configure this with a variable that you use everywhere in the method, so you don't have different requirements at different places and risk forgetting to change it in all places.

2020-12-25 23:53 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +            output = "[No output]" if result == "" else result
Put this in a formatting helper method.

2020-12-26 14:14 UTC, Shivansh-007 commented
changes addressed @gustavwilliam !

2020-12-26 15:09 UTC, gustavwilliam requested changes
Almost there! Just a few minor tweaks.

There's also an issue with the link from hastebin not being parsed correctly. They use the format https://hastebin.com/raw/..., instead of https://hastebin.com/.../raw/.

2020-12-26 15:09 UTC, gustavwilliam commented on bot/exts/utils/_eval_helper.py
> +                f"{i:03d} | {line}" for i, line in enumerate(result.split("\n"), 1)
```suggestion
                f"{i:02d} | {line}" for i, line in enumerate(result.split("\n"), 1)
```
We only need two decimal places.

2020-12-26 15:09 UTC, gustavwilliam commented on bot/exts/utils/_eval_helper.py
> +        if lines > 10:
You are using the literals 10 and 11 here to indicate the maximum amount of lines. Put the 11 in a variable (attribute) instead, so it's easily modified from one place.

2020-12-26 15:09 UTC, gustavwilliam commented on bot/exts/utils/eval.py
> +        async with ctx.typing():
Put this line (make it look like the bot is typing) on the very first line of the command. Even while it's parsing the input, I want it to look like the bot is typing.

2020-12-26 15:58 UTC, gustavwilliam requested changes
The bot also doesn't respond when sending the following:
```
!e py
for I in range(11):
    print("Hello, world!"*10)
```
That's something to fix into before merging.

2020-12-26 15:58 UTC, gustavwilliam commented on bot/exts/utils/_eval_helper.py
> +        if result.count("\n") > 40:
Shouldn't this use the max line limit?

2020-12-26 15:58 UTC, gustavwilliam commented on bot/exts/utils/_eval_helper.py
> +            program_output = result[:500] + "\n... (truncated - too many lines)"
Why is it only displaying 500 characters, but truncating once it gets over 1991?

2020-12-26 23:26 UTC, Shivansh-007 commented on bot/exts/utils/_eval_helper.py
> +            program_output = result[:500] + "\n... (truncated - too many lines)"
It is displaying only 500 characters since there would be the output in the haste in link also hence I didn’t see a need for it so a greater output. Also some characters are taken by the embed so it would reduce the mas value you can put for the embed. (1024 characters)

2020-12-26 23:27 UTC, Shivansh-007 commented on bot/exts/utils/_eval_helper.py
> +        if result.count("\n") > 40:
This in case we have to put the output in a hastebin link, hence it won’t be needing max line variable.

2020-12-26 23:28 UTC, Shivansh-007 commented
> The bot also doesn't respond when sending the following:
> 
> ```
> !e py
> for I in range(11):
>     print("Hello, world!"*10)
> ```
> 
> That's something to fix into before merging.

Am not sure why that is happening currently , but will do the needful.

2020-12-27 01:40 UTC, gustavwilliam commented on bot/exts/utils/_eval_helper.py
> +        if result.count("\n") > 40:
That doesn't really make sense imo.

2020-12-27 01:43 UTC, gustavwilliam approved these changes
LGTM. It seems to work from my testing and this review has been going on for quite some time now. Let's get a second review on this and merge it soon.

Thanks for this PR! The output looks solid from after we went through it and did all modification. I like this command and it just works like you expect it to.

2020-12-27 01:56 UTC, Xithrius requested changes
Looks good to me besides a few return annotations and a return statement.

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/eval.py
> +    def __init__(self, bot: Bot):
```suggestion
    def __init__(self, bot: Bot) -> None:
```

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +    def __init__(self, language: str):
```suggestion
    def __init__(self, language: str) -> None:
```

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +            return None
`return` returns `None` by default.
```suggestion
            return
```

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +    def __init__(self, language: str):
```suggestion
    def __init__(self, language: str) -> None:
```

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +    ):
```suggestion
    def __init__(
        self,
        language: str,
        code: str,
        inputs: str = "",
        compiler_flags: Optional[list] = None,
        command_line_options: Optional[list] = None,
        args: Optional[list] = None,
    ) -> None:
```

2020-12-27 01:56 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +def _to_tio_string(couple: tuple) -> Any:
Does this not return bytes?
```suggestion
def _to_tio_string(couple: tuple) -> bytes:
```

2020-12-27 02:02 UTC, Xithrius requested changes
one last thing

2020-12-27 02:02 UTC, Xithrius commented on bot/exts/utils/_eval_helper.py
> +                return data.replace(data[:16], "")  # remove token
`.replace` is a method for strings, so this method shouldn't return `Any`. This should return a `str` object.
```suggestion
    async def get_result(self) -> str:
        """Send Request to Tio Run API And Get Result."""
        async with aiohttp.ClientSession() as client_session:
            async with client_session.post(self.backend, data=self.request) as res:
                if res.status != 200:
                    logger.warning(
                        f"HttpProcessingError while getting result of code from tio api with "
                        f"status code: {res.status}"
                    )

                data = await res.read()
                data = data.decode("utf-8")
                return data.replace(data[:16], "")  # remove token
                ```

2020-12-27 02:26 UTC, Xithrius commented
LGTM

2020-12-27 02:26 UTC, Xithrius approved these changes
LGTM

2020-12-27 02:28 UTC, merged