Isgurkan command And gurkancount command
gurkult/gurkbot pull request #33
Opened 2020-12-27 10:49 UTC by saiTama-max

Added 2 commands isgurkan, gurkancount, in a cog called GurkanStats, inside the utils extension, isgurkan checks if a user or another name is a gurkan and what is the gurkan rate (the rate by which the gurkan matches the name), gurkancount gives the number of gurkans in the server and the percentage
Closes #2

2020-12-27 11:35 UTC, ReneganRonin approved these changes
Code looking good. No messy parts so far as intended.

2020-12-27 11:38 UTC, ReneganRonin commented
I need to fix the linting first

2020-12-27 11:52 UTC, zeeshanok commented
Can you make the gurkan name checking logic into its own function in `utils`? I feel like we could use this gurkanrate thing elsewhere.

2020-12-27 11:53 UTC, saiTama-max commented
yeah sure, should i make it a global function then?

2020-12-27 11:54 UTC, zeeshanok commented
> yeah sure, should i make it a global function then?

Global as in in another file that is easily accessible?

2020-12-27 11:56 UTC, ReneganRonin commented
@saiTama-max can u fix the flake8 as well? do u have an editor that can do it for u?

2020-12-27 11:57 UTC, saiTama-max commented
hmm, not sure about that but i was thinking about making it inside the cog itself, but outside the cog class?

2020-12-27 11:57 UTC, saiTama-max commented
> @saiTama-max can u fix the flake8 as well? do u have an editor that can do it for u?

well actually, i already linted it with flake8 in vscode, but we are using black so i am reformatting rn

2020-12-27 12:01 UTC, saiTama-max commented
also @zeeshanok, to get the rate, its already one line `gurk_rate = process.extractOne("gurkan", [user])[1]`, here process is imported from `fuzzywuzzy`, so not sure if it is big enough to be put in a function :thinking:

2020-12-27 12:05 UTC, codephile1221 reviewed
Hello! I went through your commits and felt they are pretty solid. There are a few things you could do differently though.

Overall, I like the work you did and think you did a good job... Keep it up!

2020-12-27 12:05 UTC, codephile1221 commented on bot/exts/utils/gurkan_stats.py
> +        aliases=("gurkrate", "gr", "isgurk", "gurkanrate", "gurkanr8", "gurkr8")
I don't feel these many aliases are necessary. One or two will suffice.

2020-12-27 12:11 UTC, codephile1221 commented
I went through your code before you linted the code in [this commit] (https://github.com/gurkult/gurkbot/pull/33/commits/20e8ed390f18119919f6aa8646d8e7f33784996c).
That's the reason my comments are shown as "outdated".

2020-12-27 12:29 UTC, codephile1221 reviewed
Just mentioning a small suggestion to adhere to PEP8 naming convention for functions,

2020-12-27 12:29 UTC, codephile1221 commented on bot/exts/utils/gurkan_stats.py
> +    async def gurkancount(self, ctx: Context):
```suggestion
    @command(
        name="gurkancount",
        brief="Get the count of people who are valid gurkans",
        help="""gurkancount

            To get the count of people who have gurk/urkan in their names i.e,
            they are valid gurkans
            """,
        aliases=("gurkanc", "gcount", "gc", "gurkcount", "gurkc"),
    )
    async def gurkan_count(self, ctx: Context):
```

2020-12-27 12:29 UTC, codephile1221 commented on bot/exts/utils/gurkan_stats.py
> +    async def isgurkan(self, ctx: Context, user: Union[Member, str] = None):
```suggestion
    @command(
        name = "isgurkan",
        help="""isgurkan [user/text (optional)]

                Get an embed based on the gurkan rate of the person.
            """,
        brief="Get an embed on the rate of gurkanity of a user",
        aliases=("gurkrate", "gr", "isgurk", "gurkanrate", "gurkanr8", "gurkr8"),
    )
    async def is_gurkan(self, ctx: Context, user: Union[Member, str] = None):
```

2020-12-27 12:29 UTC, Shivansh-007 reviewed
Looks good, just few changes, also use of logger statements would be good,

2020-12-27 12:29 UTC, Shivansh-007 commented on bot/bot.py
> +intents = Intents.default()
Shouldn't this code be moved after the `Bot` class?

2020-12-27 12:29 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +
Wrong imports order, (run `pipenv run lint` to see the fixes).

2020-12-27 12:29 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +        help="""gurkancount
Move brief below `help` or you can move `aliases` above brief

2020-12-27 12:29 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +    async def isgurkan(self, ctx: Context, user: Union[Member, str] = None):
```suggestion
    async def isgurkan(self, ctx: Context, user: Union[Member, str] = None) -> None:
```

2020-12-27 12:29 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +    async def gurkancount(self, ctx: Context):
```suggestion
    async def gurkancount(self, ctx: Context) -> None:
```

2020-12-27 13:03 UTC, Shivansh-007 commented
> https://github.com/gurkult/gurkbot/issues/2#issuecomment-751464497
quoting vester, you can use the colours from the constants folder

2021-01-02 15:05 UTC, gustavwilliam requested changes
Thanks! Nice PR. There are a few things I'd like to see changed before we're ready to merge.

2021-01-02 15:05 UTC, gustavwilliam commented on bot/exts/utils/gurkan_stats.py
> +            title = ":cucumber: Gurkan"
The actual check for if someone is gurkan should be the same as the one that counts the total number of gurkans in a server. This helps with consistency.

2021-01-02 15:05 UTC, gustavwilliam commented on bot/exts/utils/gurkan_stats.py
> +        return process.extractOne("gurkan", [target])[1]
This command seems to do different things depending on how it's run:
1. Get the amount of gurkans in a server
2. Get the gurkan rate of one user

Break this up into two functions, one for checking how gurkan someone is or if they're a gurkan, and one for checking the number of gurkans in a server. This would help make this even more solid.

2021-01-03 14:10 UTC, vivax3794 commented
I have redirected this pr to main, following issue #61

2021-01-03 14:11 UTC, vivax3794 commented
I have redirected this pr to main, following issue #61

2021-01-05 04:03 UTC, Arnav-2004 commented on bot/exts/utils/gurkan_stats.py
> +            await ctx.send(f"Whoa!! Everyone is a gurkan! All {gurkans} members!")
The color I am using is 0x32A05A

2021-01-07 07:45 UTC, Shivansh-007 requested changes

2021-01-07 07:45 UTC, Shivansh-007 commented on Pipfile
> +python-levenshtein = "*"
Instead of using `*` version, stick to a definite one, like discord.py.
```suggestion
fuzzywuzzy = "~=0.18.0"
python-levenshtein = "~=0.12.0"
```
Also i can't see where `python-levenshtein` is being used.

2021-01-07 07:45 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +            title = f"🥒 {gurkans} members"
Shift the gurkan emoji o constants.py

2021-01-07 07:45 UTC, Shivansh-007 commented on bot/exts/utils/gurkan_stats.py
> +        title = ""
I don't see a need to define this variables here, since there is `else` statement to `if-else` code block.
```suggestion

```

2021-01-07 11:26 UTC, gustavwilliam requested changes
Almost there.

2021-01-07 11:26 UTC, gustavwilliam commented on bot/exts/utils/gurkan_stats.py
> +    return bool(re.search(r"gurk|urkan", target))
This should be a helper in `bot/utils`. We really want the same check to be used all across the bot. Other current PRs also implement a similar check, but we're working on putting the function in *one* place.

2021-01-07 11:54 UTC, saiTama-max commented on bot/exts/utils/gurkan_stats.py
> +    return bool(re.search(r"gurk|urkan", target))
alright

2021-01-07 12:59 UTC, gustavwilliam requested changes
Excellent. Just move the files to a 'gurkan' category (see review comment) and I'll approve this.

2021-01-07 12:59 UTC, gustavwilliam commented on bot/exts/utils/gurkan_stats.py
> +
Right, so, these entire commands aren't really utils, so they would probably be better under `bot/exts/gurkan` (a new category for gurkan-related cogs.

2021-01-07 13:01 UTC, saiTama-max commented on bot/exts/utils/gurkan_stats.py
> +
alright then :smile:

2021-01-07 13:09 UTC, gustavwilliam approved these changes
Thanks! LGTM.

2021-01-07 13:11 UTC, gustavwilliam commented
Huh, GitHub just did something really weird — sorry about requesting all those reviews.

@saiTama-max could you resolve the merge conflicts?

2021-01-07 13:12 UTC, saiTama-max commented
yeah let me see

2021-01-07 13:17 UTC, saiTama-max commented
@gustavwilliam :+1:

2021-01-07 13:20 UTC, merged