Feature/error handler
gurkult/gurkbot pull request #34
Opened 2020-12-27 12:22 UTC by Shivansh-007

2020-12-27 12:22 UTC, Shivansh-007 commented
Closes #29

2020-12-28 08:55 UTC, Xithrius requested changes
This is all I have for now.

2020-12-28 08:55 UTC, Xithrius commented on bot/constants.py
> +]
You just copied all this from sir-lancebot. I think we should create our own responses.

2020-12-28 08:55 UTC, Xithrius commented on bot/utils/checks.py
> +        if redirect_channel:
I think this should be more explicit.
```suggestion
        if redirect_channel is not None:
```

2020-12-28 09:07 UTC, fisher60 submitted a review, later dismissed
A few nit-picky things for now.

2020-12-28 09:07 UTC, fisher60 commented on bot/utils/checks.py
> +                f" here. Please use the <#{redirect_channel}> channel instead"
```suggestion
                f"Here, please use the <#{redirect_channel}> channel instead"
```

2020-12-28 09:07 UTC, fisher60 commented on bot/constants.py
> +]
This could make sense as a YAML file, to increase organization and make the constants file a bit more manageable.

2020-12-28 09:50 UTC, Shivansh-007 commented on bot/constants.py
> +]
Yes, but i couldn't come up with them, So i just took them, if someone comes up they can just put them here or ping me on discord.

2020-12-28 09:51 UTC, Shivansh-007 commented on bot/constants.py
> +]
Alrightt!

2020-12-28 09:57 UTC, Xithrius commented
Please make the commit messages more descriptive. "Update <your file here>" doesn't tell us anything.

2020-12-28 10:23 UTC, codephile1221 reviewed
Hey, just a few things I wanted clarified

2020-12-28 10:23 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +            return  # Exit early to avoid logging.
why is this comment put here?
I don't see any logging being avoided.
Did you mean to put this [logging statement](https://github.com/gurkult/gurkbot/pull/34/files#diff-9a635f11cfc93b25d2c440dc75d5f492d682fd9770feebc4e5216000929b9ab9R51-R56) outside the `if-elif-else` block?

2020-12-28 10:23 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +        if not dev_alerts:
```suggestion
        if dev_alerts is None:
```
You could be more explicit here, too.

2020-12-28 10:23 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +        if isinstance(error, commands.CommandNotFound):
Do we really want to log `commands.CommandNotFound` error?

2020-12-28 10:25 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +        if isinstance(error, commands.CommandNotFound):
The current structure means that even `CommandNotFound` is logged. This might be a bit spammy.

2020-12-28 10:48 UTC, Shivansh-007 commented on bot/exts/backend/error_handler.py
> +            return  # Exit early to avoid logging.
Ah! Earlier there was no unhandled error function so it was getting used but now we have and i forgot to remove that! Thanks for pointing it out

2020-12-28 10:48 UTC, Shivansh-007 commented on bot/exts/backend/error_handler.py
> +        if not dev_alerts:
Done!

2020-12-28 10:50 UTC, Shivansh-007 commented on bot/exts/backend/error_handler.py
> +        if isinstance(error, commands.CommandNotFound):
Hmmm, we can not log them, but i kept it since in future we may implement something on that.

2020-12-28 10:57 UTC, Shivansh-007 commented on bot/exts/backend/error_handler.py
> +        if isinstance(error, commands.CommandNotFound):
Done!

2020-12-28 11:01 UTC, Xithrius commented
@Shivansh-007 This was probably a mistake and I don't blame you for doing it, but *please* remember to change these types of commits in the future. 

Examples being 72a37527d7d0c71b232b152822485d779e3bb568 and 04379b8's commit messages.

2020-12-28 11:02 UTC, Shivansh-007 commented
Alright No Problem!

2020-12-28 11:16 UTC, ReneganRonin commented
@Shivansh-007 u can always use `git commit --amend` to redefine your commit. So Xithy won't and Fishy will find it easier to review your code.

2020-12-28 11:24 UTC, codephile1221 reviewed
Looks like unexpected errors are logged twice ( in  [lines 51 to 56](https://github.com/gurkult/gurkbot/pull/34/files#diff-9a635f11cfc93b25d2c440dc75d5f492d682fd9770feebc4e5216000929b9ab9R56-R61) and in [handle_unexpected_error](https://github.com/gurkult/gurkbot/pull/34/files/c3ed800bb5721b3600800e97bb8596fe3791efd4#diff-9a635f11cfc93b25d2c440dc75d5f492d682fd9770feebc4e5216000929b9ab9R149-R152 )

2020-12-28 11:24 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +        )
```suggestion
 
 ```
this part could be moved

2020-12-28 11:24 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +            return  # Exit early to avoid logging.
```suggestion
            return  # Exit early to avoid logging.

        logger.debug(
            f"Error Encountered: {type(error).__name__} - {str(error)}, "
            f"Command: {ctx.command}, "
            f"Author: {ctx.author}, "
            f"Channel: {ctx.channel}"
        )
```
Logging can be done ere to ensure that unhandled errors are not logged twice.

2020-12-28 11:24 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +            return
```suggestion
  
```
This could also be moved

2020-12-28 11:24 UTC, codephile1221 commented on bot/exts/backend/error_handler.py
> +        if isinstance(error, commands.UserInputError):
```suggestion
       if isinstance(error, commands.CommandNotFound):
            return  # exiting early to avoid logging
        elif isinstance(error, commands.UserInputError):
```
After taking my suggestions into consideration, `CommandNotFound` can be part of the `if-elif-else` block again.

2020-12-28 11:39 UTC, codephile1221 commented
@Shivansh-007 Note:  The `return` statement in the handling of each error will need to be removed, if you decide to take my duggestions into consideration.

2021-01-02 15:07 UTC, gustavwilliam commented
Do we have any progress on this? It's a high priority task that we should get merged quite soon.

2021-01-03 02:16 UTC, Shivansh-007 commented
Waiting for @fisher60 and @Xithrius to do the final review!

2021-01-03 03:57 UTC, Xithrius commented
@Shivansh-007 to what extent have you tested this error catcher?

2021-01-03 06:35 UTC, Xithrius reviewed
It seems that this cog doesn't need major refactoring like I said. 

Last time I looked at it was very early one morning and I thought a bunch of statements were being repeated.

Looks pretty good to me, will merge once confirmed that logging errors does actually work.

2021-01-03 06:35 UTC, Xithrius commented on bot/utils/checks.py
> +        super().__init__(error_message)
Why is this here? I don't see any usage of it inside or outside of this PR.

2021-01-03 11:07 UTC, Shivansh-007 commented on bot/utils/checks.py
> +        super().__init__(error_message)
Ah yes! I thought it could have been useful check, hence put it in.

2021-01-03 14:10 UTC, vivax3794 commented
I have redirected this pr to main, following issue #61

2021-01-03 21:27 UTC, Xithrius commented
@Shivansh-007 Please resolve the conflicts before continuing.

2021-01-07 04:11 UTC, Xithrius approved these changes
LGTM

2021-01-07 11:15 UTC, gustavwilliam requested changes
Overall, this looks good. Just a few things.

2021-01-07 11:15 UTC, gustavwilliam commented on bot/constants.py
> +    devalerts = int(os.getenv("CHANNEL_DEVALERTS", 123456789123456789))
```suggestion
    devalerts = int(os.getenv("CHANNEL_DEVALERTS", 796695123177766982))
```
I've created a `#dev-alerts` channel in the main server now.

2021-01-07 11:15 UTC, gustavwilliam commented on bot/constants.py
> +    announcements = int(os.getenv("CHANNEL_ANNOUNCEMENTS", 123456789123456789))
Is this for the regular announcements channel? Why do we need this?

2021-01-07 11:15 UTC, gustavwilliam commented on bot/constants.py
> +
Could you add a comment about what server these default IDs are for? If someone looks through the code, it would be nice to know if the IDs are for the test or main server.

2021-01-07 11:15 UTC, gustavwilliam commented on bot/constants.py
> +class Colours:
We should have he default gurkan green and yellow of the crown here. These are the two most commonly used colors for embeds.

We could discuss the rest of the colors in `#dev-branding`, but I'm fine with looking at the other colors in the future, and getting this merged with the two colors I mentioned in the beginning of the message.

2021-01-07 11:15 UTC, gustavwilliam commented on bot/utils/checks.py
> +                f"Here, please use the <#{redirect_channel}> channel instead"
```suggestion
                f" here. Please use the <#{redirect_channel}> channel instead"
```
I believe this would add capitalization and a grammatically incorrect comma in the message.

2021-01-07 13:31 UTC, Shivansh-007 commented
Mentioned the changes @gustavwilliam

2021-01-07 13:41 UTC, gustavwilliam submitted a review, later dismissed
I have not tested this. As a code review, it looks good.

2021-01-07 14:58 UTC, Akarys42 requested changes
We reverted this PR as it broke the container setup.

I left a few comments while I was on it, including what broke the container. https://github.com/gurkult/gurkbot/pull/68/commits/2e2d67593bab5aef2b78d51001c86f3a59555b49 should also be applied here.

2021-01-07 14:58 UTC, Akarys42 commented on .env-example
> +CHANNEL_DEVALERTS=""
Those two environments variables should be added to the `docker-compose.yml` file.

2021-01-07 14:58 UTC, Akarys42 commented on Pipfile
> +loguru = "*"
Please repin this to `"~=0.5.3`

2021-01-07 14:58 UTC, Akarys42 commented on Pipfile
> -PyYAML = "~=5.3.1"
I think we still need `PyYAML`.

2021-01-07 14:58 UTC, Akarys42 commented on Pipfile
> +fuzzywuzzy = "==0.18.0"
This seems to currently block the container from building, can you investigate this? I can do it if you prefer.

2021-01-07 14:58 UTC, Akarys42 commented on bot/constants.py
> +    devalerts = int(os.getenv("CHANNEL_DEVALERTS", 123456789123456789))
Please commit this.

2021-01-07 14:58 UTC, Akarys42 commented on bot/constants.py
> +    invalid = "❌"
You should use the Unicode point (in the format of `\uXXXX`) to avoid encoding errors.

2021-01-07 14:58 UTC, Akarys42 commented on bot/resources/bot_replies.yml
> +ERROR_REPLIES: ["Please don't do that.", "You have to stop.", "Do you mind?", "In the
I think we should put those one per line.

2021-01-08 04:38 UTC, Xithrius approved these changes
LGTM

2021-01-08 08:09 UTC, Akarys42 approved these changes
LGTM!

For the record, there have been some git issues here where an erroneous PR ended up in this PR, please disregard my previous review.

2021-01-08 08:10 UTC, merged