provided better error message for when the token is missing
gurkult/gurkbot pull request #42
Opened 2020-12-30 17:22 UTC by vivax3794

raises a better error when the token is None

2020-12-31 02:11 UTC, Shivansh-007 approved these changes

2020-12-31 03:07 UTC, gustavwilliam requested changes
Thanks. Just a minor tweak.

2020-12-31 03:07 UTC, gustavwilliam commented on bot/bot.py
> +                "token value is None, make sure you have it set in .env"
```suggestion
                "token value is None. Make sure you have it set in .env"
```
Minor grammar fix. Maybe there’s a better way to say “have it set.” That doesn’t *quite* work in my head. Something like “make sure you have configured the TOKEN field in .env” might be clearer.

2021-01-02 15:08 UTC, gustavwilliam approved these changes
LGTM. Thanks!

2021-01-02 15:09 UTC, merged