Send message to devlog channel on startup
gurkult/gurkbot pull request #45
Opened 2020-12-31 06:24 UTC by Shivansh-007

2021-01-01 12:40 UTC, gustavwilliam commented
In all PRs, I expect to see the following:
- A description of the feature or bug
- The general way you approached the issue
- Images, if applicable
- Other things that might be good to know about it, like edge cases and special considerations

Please update the description and I'll have a look.

2021-01-01 15:52 UTC, Shivansh-007 commented
> In all PRs, I expect to see the following:
> 
> * A description of the feature or bug
> * The general way you approached the issue
> * Images, if applicable
> * Other things that might be good to know about it, like edge cases and special considerations
> 
> Please update the description and I'll have a look.

@gustavwilliam Done!

2021-01-01 15:56 UTC, vivax3794 approved these changes
LGTM

2021-01-02 12:31 UTC, gustavwilliam requested changes
Thanks. A few changes.

2021-01-02 12:31 UTC, gustavwilliam commented on bot/constants.py
> +    devlog = int(os.environ.get("CHANNEL_DEVLOG", 622895325144940554))
The default channel ID doesn't seem quite right. The one here is actually for another server.

2021-01-02 12:31 UTC, gustavwilliam commented on bot/bot.py
> +            name="Gurk Bot",
```suggestion
            name="Gurkbot",
```
This is one word.

2021-01-02 12:31 UTC, gustavwilliam commented on bot/bot.py
> +            url="https://github.com/gurkult/gurkbot",
Let's put this in constants, so we have a single place to store the repo URL.

2021-01-03 02:17 UTC, Shivansh-007 commented on bot/bot.py
> +            url="https://github.com/gurkult/gurkbot",
Alright

2021-01-03 02:17 UTC, Shivansh-007 commented on bot/constants.py
> +    devlog = int(os.environ.get("CHANNEL_DEVLOG", 622895325144940554))
Ah yes, will fix it

2021-01-03 13:39 UTC, gustavwilliam approved these changes
Thanks! LGTM.

2021-01-03 13:41 UTC, merged