Updated README
gurkult/gurkbot pull request #47
Opened 2020-12-31 08:13 UTC by ReneganRonin

# :cucumber: Updated README

The README contains the instructions to properly run the bot. It also has a brief instruction on how to contribute. Open to new suggestions comments and whatsoever.

2020-12-31 08:17 UTC, ReneganRonin commented
Happy New Year!!! :tada:

2020-12-31 08:28 UTC, fisher60 requested changes
Looks good, just some very minor changes I think would improve the file.

2020-12-31 08:28 UTC, fisher60 commented on README.md
> +   ```
```suggestion
   ```text
   TOKEN = <Your token> # See Discord Setup above
   PREFIX = "!" # the prefix the bot should use, will default to "!" if this is not present
   ```
```

2020-12-31 08:28 UTC, fisher60 commented on README.md
> +If you want to contribute, report a problem, add a fix or want a new feature added, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request
```suggestion
If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](https://github.com/gurkult/gurkbot/compare). For those who want to contribute, see [Dev Installation](#Dev-Installation).
```

2020-12-31 08:38 UTC, ReneganRonin reviewed
Few minor changes. Ready to merge.

2020-12-31 09:27 UTC, Shivansh-007 requested changes
Also you can say to lint before push.

2020-12-31 09:27 UTC, Shivansh-007 commented on README.md
> +2. Create a new branch by `git branch -b <name of new branch> main` or `git switch -c <name of new branch>`. Make sure the new branch name is related to feature or fix you have in mind.
You can just use `git checkout -b <branchname>`

2020-12-31 09:31 UTC, ReneganRonin commented on README.md
> +2. Create a new branch by `git branch -b <name of new branch> main` or `git switch -c <name of new branch>`. Make sure the new branch name is related to feature or fix you have in mind.
Uh no. This is to make sure the new branch is based off from the `main` branch.

2020-12-31 15:43 UTC, vivax3794 requested changes
just some minor changes

2020-12-31 15:43 UTC, vivax3794 commented on README.md
> +   pipenv run python -m bot
these commands have scripts defiend in the Pipfile that makes it easier to run them, it is also not needed  to enter the pipenv shell to start the bot. 
```suggestion
   pipenv run precommit

   # Optionally: run pre-commit hooks to initialize them.
   pipenv run lint
   
   # Run the bot
   pipenv run start
```

2020-12-31 15:43 UTC, vivax3794 commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
generally there should always be a issue before a pr

2020-12-31 16:19 UTC, ReneganRonin commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
thanks for pointing out some mistakes. but i think there is a high chance this PR will be closed without getting merged because @gustavwilliam will want to write the README on his own.

2020-12-31 16:20 UTC, ReneganRonin commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
> generally there should always be a issue before a pr

there is. issue #43

2020-12-31 16:25 UTC, vivax3794 commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
I meant the wording makes it sound like opening a issue is optional
> you can ***either*** open a new issue ***or*** open a new pull request

2020-12-31 16:28 UTC, ReneganRonin commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
ah alright

2021-01-01 02:16 UTC, ReneganRonin commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
@vivax3794 What do u think? I rephrased it so people get discouraged opening a pull request.

2021-01-02 15:11 UTC, gustavwilliam commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can either [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose) or [open a new pull request](
> i think there is a high chance this PR will be closed without getting merged because @gustavwilliam will want to write the README on his own.
That won't be an issue. I'll work on the contributing guide, but not the README. I'm looking forward to seeing this in action.

2021-01-02 16:01 UTC, vivax3794 requested changes
just some small things

2021-01-02 16:01 UTC, vivax3794 commented on README.md
> +
you forgot to close this code block

2021-01-03 02:19 UTC, Shivansh-007 commented on README.md
> +   ```
Maybe you can show how to lint the code ( `piping run lint` )

2021-01-03 05:42 UTC, ReneganRonin commented on README.md
> +   ```
you mean `pipenv run lint`

2021-01-04 22:39 UTC, Shivansh-007 commented on README.md
> +   ```
Yeah, stupid autocorrect.

2021-01-05 08:25 UTC, ReneganRonin commented on README.md
> +If you want to contribute, report a problem, add or suggest a new fix or feature, you can [open a new issue](https://github.com/gurkult/gurkbot/issues/new/choose). We generally discourage you to [ope
Does the wording make sense now @vivax3794 ?

2021-01-05 08:26 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-01-05 13:21 UTC, vivax3794 approved these changes
LGTM

2021-01-10 02:15 UTC, gustavwilliam commented
@fisher60 have your issues been addressed? I'd like to get this merged soon.

2021-01-10 02:22 UTC, gustavwilliam requested changes
Just a minor thing.

2021-01-10 02:22 UTC, gustavwilliam commented on README.md
> +The official bot for [**THE GURKULT OPEN SOURCE COMMUNITY - DISCORD SERVER**](https://bit.ly/Gurkult-Discord).
```suggestion
The official bot for [the Gurkult](https://gurkult.com/discord) — an open source community with the aim of bringing people together.
```
This looks a bit less frightening imo.

2021-01-10 02:27 UTC, gustavwilliam approved these changes
Sure, let's do this. Thanks.

2021-01-10 02:29 UTC, merged