Added commands for GitHub
gurkult/gurkbot pull request #52
Opened 2020-12-31 15:04 UTC by YuvrajGeek

## Current Commands:

- contributors
- `gitsearch users <username>` for searching users and `gitsearch repos <reponame>` for searching repositories. Help text on incorrect command syntax has been availed. Only the Top 10 results are sent in the embed.

If there are less then 3 results for either users or repos the user might be requesting something very specific. In that case, the bot sends a special embed for the first of the 3 results.

Future commands for GitHub can be added in the same Cog and under the same category.

2020-12-31 15:57 UTC, vivax3794 requested changes

2020-12-31 15:57 UTC, vivax3794 commented on Pipfile
> +requests = "*"
I think we should be using a async request lib, the eval command used aiohttp (wich is included in discord.py), but there was [talk about](https://discord.com/channels/789192517375623228/789295038315495455/790605363455459368) using [aiohttp-requests](https://pypi.org/project/aiohttp-requests/) wich should only be adding `await` in most places.

2020-12-31 15:57 UTC, vivax3794 commented on bot/exts/utils/github.py
> +PREFIX = os.getenv('PREFIX')
you should be using the prefix value from constant.py since that has a default one in the case one is not provided in the .env

2020-12-31 15:57 UTC, vivax3794 commented on bot/exts/utils/github.py
> +	async def gitsearch(self, ctx, what,*,term):
I think this would work better as 2 subcommands

2020-12-31 15:57 UTC, vivax3794 commented on requirements.txt
> +yarl==1.5.1
any reasons for this to be commited seeing as we have the Pipfile.

2020-12-31 16:13 UTC, Shivansh-007 requested changes
Make helper functions for the cog.

2020-12-31 16:13 UTC, Shivansh-007 commented on Pipfile
> +requests = "*"
Also specifying the library versions is also helpful, and you will have to create a `http session` in the `bot.py`.

2020-12-31 16:13 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +	def __init__(self, bot:Bot):
```suggestion
	def __init__(self, bot:Bot) -> None:
```

2020-12-31 16:13 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +	async def contributors(self, ctx):
```suggestion
	async def contributors(self, ctx: commands.Context) -> None:
```

2020-12-31 16:13 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +	async def gitsearch(self, ctx, what,*,term):
Similarly add annotations here too.

2020-12-31 16:13 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +				# here ************* here ************ here*************
What is this comment for? Maybe word it better

2020-12-31 16:13 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +				if len(response['items']) > 3:
Don’t hardcode these values.

2020-12-31 16:29 UTC, YuvrajGeek commented on requirements.txt
> +yarl==1.5.1
many people out there dont use pipenv, let this just be there cuz its a lot easier to install packages from requirements.txt 
you know, just in case

2020-12-31 16:33 UTC, vivax3794 commented on requirements.txt
> +yarl==1.5.1
but it is a lot easier to run the bot, setup precommit hooks, ect with pipenv

2020-12-31 16:34 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +				if len(response['items']) > 3:
which values? the thumb url ?

2020-12-31 23:47 UTC, ReneganRonin commented on requirements.txt
> +yarl==1.5.1
> many people out there dont use pipenv, let this just be there cuz its a lot easier to install packages from requirements.txt 
> 
> you know, just in case
> 
> 

As much as I like to include requirements.txt, I do not want it included because I would like it as uniform as possible. We should use only pipenv. Also, this is a learning opportunity for them to use pipenv and know how it works. @gustavwilliam What do you think?

2021-01-01 05:43 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +				# here ************* here ************ here*************
Ahh, I was just opening another project so just for myself to know where I left.

2021-01-01 05:48 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +PREFIX = os.getenv('PREFIX')
Done.

2021-01-01 05:49 UTC, YuvrajGeek commented on requirements.txt
> +yarl==1.5.1
Would be deleted in the next PR.

2021-01-01 16:37 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +				if len(response['items']) > 3:
Please Elaborate a Bit.

2021-01-02 01:36 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +				if len(response['items']) > 3:
The thumbnail URL should be a constant of the file.

2021-01-02 01:38 UTC, Shivansh-007 commented
There is no need to edit the  `bot.py` and `eval.py` File.

2021-01-02 02:02 UTC, Shivansh-007 requested changes

2021-01-02 02:02 UTC, Shivansh-007 commented on bot/exts/utils/github.py
> +def setup(bot):
```suggestion
def setup(bot: Bot) -> None:
    """Load the cog."""
```

2021-01-02 05:20 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +            if len(response['items']) > 3:
They mean that if the API responds with 3 or lesser results, it might be that the user is trying to request something specific or something popular. I can put a comment there to let the contributors know.

2021-01-02 07:33 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +from discord import Embed
Okay, should I take the colors from `eval.py` and put them into `contstants.py` so that they can be imported just as for all the files. Also, the `GREEN` is the theme color so that is supposed to be in the `constants.py` file.

2021-01-02 07:33 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +from bot.constants import PREFIX
It was supposed to be added in the help text when the user types invalid syntax for the command. Sorry, but I missed this point while commiting the changes.

2021-01-02 07:33 UTC, YuvrajGeek commented on Pipfile
> +requests = "*"
> I think we should be using a async request lib, the eval command used aiohttp (wich is included in discord.py), but there was [talk about](https://discord.com/channels/789192517375623228/789295038315495455/790605363455459368) using [aiohttp-requests](https://pypi.org/project/aiohttp-requests/) wich should only be adding `await` in most places.

Done.

2021-01-02 09:50 UTC, YuvrajGeek commented on bot/exts/utils/github.py
> +            if len(response['items']) > 3:
They mean that if the API responds with 3 or lesser results, it might be that the user is trying to request something specific or something popular. I can put a comment there to let the contributors know.

2021-01-02 12:11 UTC, closed without merging