Added !subscribe and !unsubscribe command
gurkult/gurkbot pull request #55
Opened 2021-01-01 16:16 UTC by Arnav-2004

Related To: issue#31

Below are the code snippets on how the !subscribe and !unsubscribe commands work
![test1](https://user-images.githubusercontent.com/70969910/103442276-bae19880-4c7a-11eb-9515-6af5da35c22f.png)
![test2](https://user-images.githubusercontent.com/70969910/103442280-be751f80-4c7a-11eb-9f7f-89a80b6a6ed3.png)

2021-01-01 16:18 UTC, Shivansh-007 requested changes
Run `pipenv run lint ` and have a look at the comments in the old pr

2021-01-01 16:18 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +<<<<<<< HEAD
Remove the merge conflict code.

2021-01-01 16:18 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +			announcements_id = 793864455527202849
Make these constants

2021-01-01 16:18 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +    bot.add_cog(Subscription(bot))
Add new line

2021-01-01 16:20 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +intents = discord.Intents.all()
Also remove this code, it is already present in `bot.py`

2021-01-01 16:32 UTC, Inheritanc-e reviewed
Remove complicated bits of code.

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +			announcements_id = 793864455527202849
Use utils.get or guild.get_role, instead of looping over the users roles.
You could just simplify this to
```py
announcement_role = utils.get(guild.roles,  name='Announcements')
polls_role = utils.get(guild.roles, name='Polls')
```

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +			if announcements_role in ctx.author.roles:
Use one if statement instead of two.

```py
if announcement_role in ctx.author.roles and polls_role in ctx.author.roles
```

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +		if ctx.message.content == 'a!subscribe':
Use the parameters instead of checking the command content.
```py
if not announcements and not polls
```

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +		elif ctx.message.content == 'a!subscribe announcements' or ctx.message.content == 'a!subscribe announcement':
Use the parameters instead of using the command content.

```py
elif announcements.lower() in ['announcement' ,'announcements']
```

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +		elif ctx.message.content == 'a!subscribe polls' or ctx.message.content == 'a!subscribe poll':
Use parameters instead of checking command content.
```py
elif polls.lower() in ['poll' ,'polls']
```

2021-01-01 16:32 UTC, Inheritanc-e commented on bot/exts/utils/subscription.py
> +	async def unsubscribe(self, ctx: Context, announcements:str=None, polls:str=None) -> None:
Sane as the subscribe command.

2021-01-01 18:55 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +		elif ctx.message.content == 'a!subscribe announcements' or ctx.message.content == 'a!subscribe announcement':
NoneType doesn't have lower() but `elif announcements in ['announcement', 'announcements']` would work

2021-01-01 19:01 UTC, vivax3794 requested changes

2021-01-01 19:01 UTC, vivax3794 commented on bot/exts/utils/subscription.py
> +    @client.command()
you should be using `commands.command()`

2021-01-01 19:01 UTC, vivax3794 commented on bot/exts/utils/subscription.py
> +client = commands.Bot(command_prefix="a!")
why are you defining a new client here?

2021-01-01 19:18 UTC, codephile1221 requested changes
Hey Arnav, I haven't gone though the full PR thoroughly yet but here are some things you can consider.
I'll give you further feedback later.

2021-01-01 19:18 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +client = commands.Bot(command_prefix="a!")
By convention, `bot` is used in favour of `client` in order to be clear to others that it stands for an instance of `commands.Bot`.
However, this line isn't need here anyway and should be removed.

2021-01-01 19:18 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +color = 0x32A05A
I think we shall be able to move these to a constants file. We shall discuss this later.

2021-01-01 19:18 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +polls_id = 793864455527202848
this can definitely go in `constants.py`

2021-01-01 19:18 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +    @client.command()
`client` will have to be changed to `@commands.command` after [line 8](https://github.com/gurkult/gurkbot/pull/55/files#diff-f3b2625c9076cca23a5c94b8b7d62f99df3830a77e0707be8809fcb7c9636250R8) is removed.

2021-01-03 07:18 UTC, Shivansh-007 requested changes
Some changes required otherwise code looks good.

Another Thing required is:

- Since the unsubscribe_polls and unsubscribe_announcements logic is same make a helper function for that too.
- Similary for the respective subscribe functions

(Not sure on this change, let's see what others think.)

2021-01-03 07:18 UTC, Shivansh-007 commented on bot/constants.py
> +ANNOUNCEMENTS_ID = int(os.getenv("ANNOUNCEMENTS_ID", "789978290844598272"))
Make a class named roles and inherit `typing.NamedTuple` in it. Similarly inherit it in the emojis and colors class too.

2021-01-03 07:18 UTC, Shivansh-007 commented on bot/constants.py
> +# Emojis
No need of this comment, the class name is self explanatory

2021-01-03 07:18 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +color = 0x32A05A
Since you have added it to constants no need for this in the file any more

2021-01-03 07:18 UTC, Shivansh-007 commented on bot/constants.py
> +    green_color = 0x32A05A
```suggestion
    GREEN = 0x32A05A
```

2021-01-03 07:18 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +            embed = Embed(
Since we are using embed functions at a lot of place and some code is repeating, make a embed helper function in the class itself

2021-01-03 07:23 UTC, codephile1221 requested changes
What are your thoughts on using different colors for different types of embeds?
Currently, all the embeds use green and I feel it could use some spicing up unless you feel the need for Issue #30 to be completed. However, that will stall this PR.

2021-01-03 07:24 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +color = 0x32A05A
Yea I forgot to removed this part from the file but it has been moved to `constants.py`

2021-01-03 14:09 UTC, vivax3794 commented
I have redirected this pr to main, following issue #61

2021-01-04 00:35 UTC, Shivansh-007 requested changes
Everything looks good except few changes in `constants.py`

2021-01-04 00:35 UTC, Shivansh-007 commented on bot/constants.py
> +    ANNOUNCEMENTS_ID = int(os.getenv("ANNOUNCEMENTS_ID", "789978290844598272"))
I don’t see a need to make them upper cased as they are already in a constants.py file
```suggestion
    announcements = int(os.getenv("ANNOUNCEMENTS_ID", "789978290844598272"))
```

2021-01-04 00:35 UTC, Shivansh-007 commented on bot/constants.py
> +    CONFIRMATION_EMOJI = "<:yes:794231332770938901>"
```suggestion
    confirmation = "<:yes:794231332770938901>"
```

2021-01-04 00:35 UTC, Shivansh-007 commented on bot/constants.py
> +    GREEN = 0x32A05A
```suggestion
    green = 0x32A05A
```
Sorry had suggested it to be upper case green last time.

2021-01-04 05:39 UTC, codephile1221 requested changes
Hey Arnav. Code looks good to me and seems to be perfectly functional.
Just a few things we could consider to avoid repeating  code.

2021-01-04 05:39 UTC, codephile1221 commented on bot/constants.py
> +    confirmation = "<:yes:794231332770938901>"
Would it be possible to change the name of the emoji from "`yes`" to "`confirmation`"?

2021-01-04 05:39 UTC, codephile1221 commented on bot/constants.py
> +    warning = "\u26a0"
I believe the the emoji should be specified in the format `name_emoji`.
[Smart Config](https://github.com/python-discord/smartconfig) will supposedly detect emojis based on its suffix.
```suggestion
    confirmation_emoji = "<:yes:794231332770938901>"
    warning_emoji = "\u26a0"
```

2021-01-04 05:39 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
This can be made into an helper function for subscribing.
It could take in a member, role and an optional suppress warning message flag.

Role can be `announcements` role or `polls` role and the message should reflect that accordingly.
The optional suppress warning flag is to be used when invoking `!subscribe` as we don't want to warn the user if they have a "conjugation" of the two roles.

2021-01-04 05:39 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
As for the subscribing part, either  a similar helper function  can be made for unsubscribing or an additional parameter which indicates the action done could be added to the original helper function.

2021-01-04 05:44 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
We need to also think about how a warning message will be sent if a person already has two roles since the warning is supposed to be suppressed in `!subscribe` command. Perhaps the helper could return a boolean which indicates an action has to be done and if we get two `False`es, a warning could be sent stating that the member already has both the roles.

2021-01-04 05:44 UTC, Shivansh-007 commented on bot/constants.py
> +    warning = "\u26a0"
But it is already in the Emojis class so i don't see the need of adding `_emoji` to it.

2021-01-04 05:51 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
Yes that's what i told him in my earlier review, he said he is working on that.
it can be something like:
```py
async def helper_subcribe(self, ctx: Context, role: int) -> None:
    ...
    await ctx.send(embed=embed)

async def helper_unsubcribe(self, ctx: Context, role: int) -> None:
    ...
    await ctx.send(embed=embed)
```
and
```py
async def announcements_subscribe(self, ctx: Context) -> None:
    """Subscribe to announcements by assigning yourself the role."""
    await self.helper_subsribe(ctx, Roles.announcements)
```

2021-01-04 05:52 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
The helper function will soon be made

2021-01-04 05:53 UTC, Arnav-2004 commented on bot/constants.py
> +    warning = "\u26a0"
I don't know about Smart Config a lot but will see

2021-01-04 05:53 UTC, Arnav-2004 commented on bot/constants.py
> +    confirmation = "<:yes:794231332770938901>"
Sure

2021-01-04 09:17 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-01-04 12:48 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
> We need to also think about how a warning message will be sent if a person already has two roles since the warning is supposed to be suppressed in `!subscribe` command. Perhaps the helper could return a boolean which indicates an action has to be done and if we get two `False`es, a warning could be sent stating that the member already has both the roles.

Maybe we could actually have a helper function that checks if a person has a certain role, or list with the two values `[False, True]` as a response. I think checking for a certain role instead of having a "check everything and return a list," sounds better.

2021-01-04 13:07 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
Checking for a certain role is exactly what has been done.
The helper will be called twice (once for each role).

What I suggested was that the helper could return `False` if no action has been done.
Both the calls returning False implies that  the user already has both the roles.

2021-01-04 13:11 UTC, codephile1221 reviewed
Hi! I'm really happy with how your subscribe_helper and unsubscribe_helper methods turned out.

2021-01-04 13:11 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +                await ctx.send(content=ctx.author.mention, embed=embed)
This bit could use some improvement since it looks like this block of code is essentially the same as before, but in a single method.

2021-01-04 13:12 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +                await ctx.send(content=ctx.author.mention, embed=embed)
I'll get back to you on this later :)

2021-01-04 16:29 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await ctx.send(content=ctx.author.mention, embed=embed)
There is one issue with this approach though. 
The user will get two embeds if they just do `!subscribe` (one for announcements and one for polls role)

2021-01-08 09:29 UTC, Shivansh-007 requested changes
Use the check ` InWhitelistCheckFailure` present in bot.utils to restrict this command to only bot_commands channel.

2021-01-08 09:29 UTC, Shivansh-007 commented on bot/constants.py
> +class Roles(typing.NamedTuple):
```suggestion
class Roles(NamedTuple):
```
Also move this class below `Channels`

2021-01-08 09:29 UTC, Shivansh-007 commented on bot/constants.py
> +class Emojis(typing.NamedTuple):
```suggestion
class Emojis(NamedTuple):
```
Also move this class below `Channels`

2021-01-08 09:29 UTC, Shivansh-007 commented on bot/constants.py
> +class Colors(typing.NamedTuple):
Since we already have a `Color` class, this is not needed. You can use the `gurk green` colour from the Class Below.

2021-01-13 11:29 UTC, closed without merging

2021-01-13 11:32 UTC, gustavwilliam commented
Hey @Arnav-2004, why was this closed?