Added make Gurkan
gurkult/gurkbot pull request #65
Opened 2021-01-05 04:52 UTC by RandomDev26

Closes #32

2021-01-05 04:53 UTC, RandomDev26 commented
crap, forgot to lint, I'll do it rn

2021-01-05 07:45 UTC, Shivansh-007 requested changes

2021-01-05 07:45 UTC, Shivansh-007 commented on bot/exts/utils/makegurkan.py
> +    def __init__(self, bot):
```suggestion
    def __init__(self, bot: Bot) -> None:
```
Just remember to import it:
```py
from bot.bot import Bot
```

2021-01-05 07:45 UTC, Shivansh-007 commented on bot/exts/utils/makegurkan.py
> +    async def on_member_update(self, before, after):
```suggestion
    async def on_member_update(self, before: discord.Member, after: discord.Member) -> None:
        """When the member updates their nicknames, this function will check if member is classified to be a gurkan or not."""
```
Remember to import `discord`

2021-01-05 07:45 UTC, Shivansh-007 commented on bot/exts/utils/makegurkan.py
> +    async def on_member_join(self, member):
```suggestion
    async def on_member_join(self, member: discord.Member) -> None:
         """When the member updates their username, this function will check if member is classified to be a gurkan or not."""
```

2021-01-05 07:45 UTC, Shivansh-007 commented on bot/exts/utils/makegurkan.py
> +import re
```suggestion
import re

import discord
from bot.bot import Bot
from discord.ext import commands
from discord.utils import find
```

2021-01-05 07:45 UTC, Shivansh-007 commented on bot/exts/utils/makegurkan.py
> +            role = find(lambda r: r.name == "Gurkans", after.guild.roles)
Instead of name use the id of the role, which should be present in the `constants.py` file

2021-01-10 02:06 UTC, gustavwilliam requested changes

2021-01-10 02:07 UTC, gustavwilliam commented on bot/exts/utils/makegurkan.py
> +        if re.search(r"g?urk?a?n?", str(member.name)):
Actually, I think that function is merged now, meaning you can use it.

2021-01-22 06:01 UTC, Shivansh-007 commented
@RandomDev26 Are you still working on this?

2021-01-31 21:17 UTC, gustavwilliam commented
@RandomDev26 whenever you have time, I'd like to see this merged soon. Don't work on other issues until you've finished this one.

2021-02-01 05:09 UTC, RandomDev26 commented
:thumbsup:

2021-03-07 23:19 UTC, RandomDev26 commented
I need to close this, for some reason my new commits aren't showing, I'll make a new PR

2021-03-07 23:19 UTC, closed without merging