Add Gitub Category
gurkult/gurkbot pull request #66
Opened 2021-01-05 12:59 UTC by Shivansh-007

2021-01-05 13:00 UTC, Shivansh-007 commented
Closing https://github.com/gurkult/gurkbot/issues/11

2021-01-08 12:42 UTC, codephile1221 requested changes
Heyo, Shivansh :cucumber: ! I haven't reviewed the entire PR yet, but here are some things you could look into.

2021-01-08 12:42 UTC, codephile1221 commented on bot/constants.py
> +    merge = "<:PRMerged:794119023687761941>"
```suggestion
class Emojis(NamedTuple):
    issue_emoji = "<:IssueOpen:794119024367632405>"
    issue_closed_emoji = "<:IssueClosed:794118652219359253>"
    pull_request_emoji = "<:PROpen:794118652014231562>"
    pull_request_closed_emoji = "<:PRClosed:794120818908463134>"
    merge_emoji = "<:PRMerged:794119023687761941>"
```
Please suffix `emoji` to the class variable name as it will be required once we start using [Smart Config](https://github.com/python-discord/smartconfig).

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +}
This could be moved to a constants file.
(It could potentially be moved again once we start using Smart Config, I'll get back to you on this later.)

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +            return REPO_CHANNEL_MAP[str(channel)]
This is just my preference.
```suggestion
        if channel.name in REPO_CHANNEL_MAP.keys():
            return REPO_CHANNEL_MAP[channel.name]
```

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +            return ""
```suggestion
            return None
```
oh wee, here I go explicit again.

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        repo_got_for_channel = self.get_repo(channel)
This could be named better.

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        repo_got_for_channel = self.get_repo(channel)
Could be named better.

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        repo_got_for_channel = self.get_repo(channel)
You could also call it directly in the next line.

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +                title="Errror!",
A random error reply from  `constants.py` could be used.

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +                description=f"Too many issues/PRs! (maximum of {MAX_REQUESTS})",
```suggestion
                description=f"You can specify a maximum of {MAX_REQUESTS} issues/PRs only.",
```

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +    ) -> Union[None, Embed, str]:
```suggestion
    ) -> Optional[Embed, str]:
```

2021-01-08 12:42 UTC, codephile1221 commented on bot/exts/github/github.py
> +        await ctx.send(embed=embed)
`_issues.issue()` could potentially return a string (https://github.com/gurkult/gurkbot/pull/66/files#diff-394f17177701193becda17d82d1eb7bad9a74660ccbb18032e2bd38d9a8fd793R72).

2021-01-08 12:43 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        repo_got_for_channel = self.get_repo(channel)
I'm referring to line 49.

2021-01-08 12:43 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        repo_got_for_channel = self.get_repo(channel)
I'm referring to line 49.

2021-01-08 14:32 UTC, Shivansh-007 commented
Fixed merged conflict

2021-01-08 14:32 UTC, Shivansh-007 commented
@codephile1221 Ok , thanks for the review, will mention those changes in the next commit.

2021-01-08 14:34 UTC, codephile1221 commented
I wouldn't mind if you make multiple commits for the changes.
Similar changes can be in one commit.

2021-01-08 16:10 UTC, Shivansh-007 commented on bot/exts/github/_issues.py
> +            return REPO_CHANNEL_MAP[str(channel)]
Am using the channel id and not name.

2021-01-08 18:07 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +            return REPO_CHANNEL_MAP[str(channel)]
oops, `channel.id` then.
But wouldn't `str(channel)` give you the name of the channel is string then?

2021-01-11 06:21 UTC, Shivansh-007 commented on bot/exts/github/_issues.py
> +            return REPO_CHANNEL_MAP[str(channel)]
it checks for `id` not name.

2021-01-11 07:08 UTC, codephile1221 requested changes
hello!
Few things :star2:

2021-01-11 07:08 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +}
I don't see why the keys have to be `str`
```suggestion
REPO_CHANNEL_MAP = {
    Channels.dev_reagurk: "reagurk",
    Channels.dev_gurkbot: "gurkbot",
    Channels.dev_gurklang: "py-gurklang",
    Channels.dev_branding: "branding",
}
```
3/4

2021-01-11 07:08 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +        channel: discord.TextChannel,
Currently, this parameter annotation is incorrect as you are passing in an `int` and not a channel object.
But if my suggestions are taken into consideration, it can be left as it is.
4/4

2021-01-11 07:08 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +            return None
```suggestion
        return REPO_CHANNEL_MAP.get(channel.id)
```

2021-01-11 08:11 UTC, codephile1221 requested changes
One more thing which I wanted to add...

2021-01-11 08:11 UTC, codephile1221 commented on bot/exts/github/_source.py
> +        embed.add_field(name="Source Code", value=f"```python\n{sanitized}\n```")
Do we really need to show part of the code to the user?
The content displayed will be mostly only the doc string, which should be ideally accessed through help command.
I feel all you need to do here is provide a link to the source code of the command in a nice embed.
You could also display a brief description of the command.

2021-01-11 10:58 UTC, codephile1221 requested changes
Hey! I'm done with the review of the whole PR :star: .
Here are some things we could discuss.

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_profile.py
> +        embed.add_field(name="Website", value=user_data["Website"])
How does looping through `userdata` to adds fields sound?
You will have keep a tuple which will contain either values that you need to add to the embed, or values that you don't want to add as fields (whichever is shorter).
Feel free to ignore this comment if you feel it doesn't add much value to the code quality.

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
As discussed, this part will need to be changed to accommodate the following usage:
```
!issue 53 gurkult/gurkbot
!issue 53 gurkbot
!issue 53
```

> **The three ways to dewit**

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +                ]
This can be a tuple.

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/github.py
> +            return
Let's handle the absence of username here instead of [get_github_info](https://github.com/gurkult/gurkbot/pull/66/files#diff-47f6432ddf370ef36c67c3320cc9bd1fea2e26bf87bc1dd1f8edc9ae21d53ddfR91-R92).
```suggestion
        if username is None:
            raise MissingRequiredArgument
  
        github_profile = _profile.GithubInfo(self.bot.http_session)
        embed = await github_profile.get_github_info(username)           
```

[1/2](https://github.com/gurkult/gurkbot/pull/66/files#diff-47f6432ddf370ef36c67c3320cc9bd1fea2e26bf87bc1dd1f8edc9ae21d53ddfR85-R92)

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_profile.py
> +            return None
```suggestion
    async def get_github_info(self, username: str) -> Embed:
        """
        Fetches a user's GitHub information.
        """
```
Adjust annotations.

[2/2](https://github.com/gurkult/gurkbot/pull/66/files#diff-28432be4eec36ad2779e0c64d0500290051c943cddc99bec6900dfddafb39a7eR30)

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/github.py
> +
I'm not sure if this block of code will get executed.
```suggestion

```
I think it's a remanent of a change you did ( `github_issue.issue`  returns an embed if an issue or PR wasn't found but it used to return `str`)

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_source.py
> +        self.max_field_length = 500
Let's name it in uppercase since it's a constant.
```suggestion
        self.MAX_FIELD_LENGTH = 500
```

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_source.py
> +            "<http://github.com/gurkult/gurkbot/blob/develop/"
1) You are using link from a branch that doesn't exist anymore.
2) You can use `BOT_REPO_URL`.

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_source.py
> +            )
```suggestion
        if len(sanitized) > self.MAX_FIELD_LENGTH:
            sanitized = (
                sanitized[: self.MAX_FIELD_LENGTH]
                + "\n... (truncated - too many lines)"
            )
```

2021-01-11 10:58 UTC, codephile1221 commented on bot/exts/github/_source.py
> +        embed.add_field(name="Source Code", value=f"```python\n{sanitized}\n```")
It has been discussed that the doc string could be removed before displaying the embed.

2021-01-11 11:02 UTC, codephile1221 commented on bot/exts/github/_issues.py
> +                ]
```suggestion
                (
                    icon_url,
                    f"[{repository}] #{number} {json_data.get('title')}",
                    issue_url,
                )
```

2021-01-13 04:20 UTC, Shivansh-007 commented on bot/exts/github/_profile.py
> +        embed.add_field(name="Website", value=user_data["Website"])
I have merged the get embed and get user information into one, since the get information and get embed were basically doing the samething.

2021-01-13 04:20 UTC, Shivansh-007 commented on bot/exts/github/_profile.py
> +        embed.add_field(name="Website", value=user_data["Website"])
So this isn't needed i guess.

2021-01-13 13:08 UTC, codephile1221 requested changes
Hi. Small things we could go through:

2021-01-13 13:08 UTC, codephile1221 commented on bot/exts/github/github.py
> +        if embed is None:
I understand that `embed` will be `None` if `source_item` isn't specified.
How about checking if `source_item` is `None` here instead of in [the inspect method](https://github.com/gurkult/gurkbot/pull/66/files#diff-612a7705b73336b9f811520d079c91f50e59a0abdf00898b8ed070846acc69b7R25-R26)?

Moreover, is it really necessary? Looks like `source_item` is a required argument.

2021-01-13 13:08 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
As discussed, this part will need to be changed to accommodate the following usage:
```
!issue 53 gurkult/gurkbot
!issue 53 gurkbot
!issue 53
```

> **The three ways to dewit**

2021-01-13 14:32 UTC, codephile1221 commented on bot/exts/github/_source.py
> +        sanitized = re.sub(doc_reg_class, "", sanitized)
...instead of using regex.

2021-01-13 15:18 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
It does. Check 53, also I mistakenly committed a debug code, will remove it in the next commit.

2021-01-13 15:19 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +        if embed is None:
What if the command is not a actual command on the bot? Then we wld need it.

2021-01-13 15:35 UTC, codephile1221 commented on bot/exts/github/github.py
> +        if embed is None:
That's not what I  meant.
`source_item` is a required argument and hence it can not be `None`, I feel. I could be wrong, do correct me then.

2021-01-13 16:20 UTC, codephile1221 requested changes

2021-01-13 16:20 UTC, codephile1221 commented on bot/exts/github/github.py
> +            await ctx.send(f"Running split user-repo on {repository}")
why do we need to send this message to the user?

2021-01-13 16:20 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
This could cause confusion when displaying usage.
```suggestion
        repository: typing.Optional[str] = None
```
You could do this, then do the following
1) if `repository` is `None`, `user = "gurkult"`
2. a) else `user, _, repository = repository.rpartition("/")`
2. b) if `user` is `""`, `user = gurkult`

2021-01-13 17:42 UTC, codephile1221 commented on bot/exts/github/github.py
> +        if embed is None:
Anyway, I'd rather have it handled here than in [the inspect method](https://github.com/gurkult/gurkbot/pull/66/files#diff-612a7705b73336b9f811520d079c91f50e59a0abdf00898b8ed070846acc69b7R25-R26).

Also, hey, let's send the link to the repo if the user does `!source`. You need to make `source_item` an optional parameter and if it's `None`, send an embed with link to the gurkbot repo and return.

2021-01-14 11:24 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +            await ctx.send(f"Running split user-repo on {repository}")
Like side earlier, I have mistakenly committed the debug code 😓

2021-01-14 14:21 UTC, codephile1221 commented on bot/exts/github/github.py
> +            await ctx.send(f"Running split user-repo on {repository}")
Oh, alright.

2021-01-14 14:21 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
@Shivansh-007 what about this?

2021-01-15 10:34 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +        if embed is None:
Alright

2021-01-15 10:38 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
Hmmm, I like the curren way, it is more understandable ig.

2021-01-16 07:30 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
the reason I don't like the current way is because the usage is technically `!issue <number> <repo> <user=''gurkult">` when we want it to be `!issue <number> <user=gurkult>/<repo>`

2021-01-16 07:31 UTC, codephile1221 commented on bot/exts/github/github.py
> +        user: str = "gurkult",
and we can technically call `<user>/<repo>` as `<repo>`.

2021-01-17 11:43 UTC, codephile1221 requested changes
Review as requested :smile: .

2021-01-17 11:43 UTC, codephile1221 commented on bot/exts/github/github.py
> +        self, ctx: commands.Context, *, source_item: str = ""
```suggestion
        self, ctx: commands.Context, *, source_item: Optional[str] = None
```
Just a small change.

2021-01-17 11:43 UTC, codephile1221 commented on bot/exts/github/github.py
> +        if source_item == "":
```suggestion
        if source_item is None:
```

2021-01-17 11:51 UTC, ReneganRonin commented on bot/exts/github/github.py
> +        if source_item == "":
This change makes sense as it will make it make it more pythonic since None is a "falsy" value.

2021-01-17 12:08 UTC, Shivansh-007 commented
Done.

2021-01-17 15:04 UTC, codephile1221 requested changes

2021-01-17 15:04 UTC, codephile1221 commented on bot/exts/github/github.py
> +        self, ctx: commands.Context, *, source_item: Optional[str] = None
```suggestion
        self, ctx: commands.Context, *, source_item: typing.Optional[str] = None
```

2021-01-18 04:29 UTC, Shivansh-007 commented on bot/exts/github/github.py
> +        self, ctx: commands.Context, *, source_item: Optional[str] = None
Yeah, had just done the `commit suggestion` and forgot to change it to `typing.Optional`
Thanks

2021-01-18 04:41 UTC, codephile1221 approved these changes
:point_right: :point_left: 

LGTM :+1: !!!

2021-01-18 07:48 UTC, ReneganRonin approved these changes
Looks good to me. :100:

2021-01-18 08:10 UTC, merged