Improved gurkanrate function
gurkult/gurkbot pull request #69
Opened 2021-01-08 05:22 UTC by saiTama-max

Removed use of fuzzywuzzy completely, now function uses regex to check the span of string match and rate is decided based upon that

2021-01-08 08:20 UTC, Akarys42 requested changes
Some little bits and pieces. You also have some merge conflicts, please resolve those.

2021-01-08 08:20 UTC, Akarys42 commented on Pipfile
> +loguru = "*"
Please repin this to `"~=0.5.3"`

2021-01-08 08:20 UTC, Akarys42 commented on Pipfile
> -PyYAML = "~=5.3.1"
I think we still need this dependency

2021-01-08 08:20 UTC, Akarys42 commented on bot/constants.py
> +    invalid = "❌"
Please use Unicode points here: respectively `\U0001f952` and `\u274c `.

2021-01-08 08:20 UTC, Akarys42 commented on bot/utils/is_gurkan.py
> +    return int((span[1] - span[0]) / len(name) * 100)
Some comments here would be nice, I have no idea how this function work

2021-01-08 08:22 UTC, codephile1221 commented
Don't forget to resolve the conflicts in `bot/constants.py` :)

2021-01-08 09:20 UTC, codephile1221 requested changes
Hey!  Just some small things you could consider.

2021-01-08 09:20 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +        gurkans = sum(gurkan_check(member) for member in members)
Instead of constructing the list with list comprehension, would it be possible to use `map()` or the following :point_down: ?
```suggestion
        gurkans = sum(gurkan_check(member.display_name) for member in ctx.guild.members)
```

2021-01-08 09:20 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +            user = ctx.author.display_name if not user else user.display_name
I'm being nitpicky here, since this wouldn't change the functionality. However, this is more explicit.
```suggestion
            user = ctx.author.display_name if user is None else user.display_name
```

2021-01-08 16:21 UTC, gustavwilliam commented on bot/exts/gurkan/gurkan_stats.py
> +            user = ctx.author.display_name if not user else user.display_name
```suggestion
            user = user.display_name if not user else ctx.author.display_name
```
I think this makes even more sense.

2021-01-08 16:33 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +            user = ctx.author.display_name if not user else user.display_name
The reasoning behind using `is not None` is that certain values are Falsy (0 for example) and might cause undesirable effect.
However, with the code as it is, such undesirable effects will not manifest (`""`, `0`, etc cannot be possible arguments as discord.py will convert them) and hence is not necessary.

2021-01-09 14:45 UTC, decorator-factory commented on bot/utils/is_gurkan.py
> +    return int((span[1] - span[0]) / len(name) * 100)
I get what it does, but I guess it could've been rewritten to be more clear. 
If the function is hard to read, the first option should be to make it more clear, not bloat it with comments.
First, you could use unpacking:
```py
def gurkan_rate(name: str) -> int:
    """Returns the rate of gurkan in the name given."""
    search = re.search(r"gurk|urkan", name.lower())
    begin, end = search.span() if search else (0, 0)
    return int((end - begin) / len(name) * 100)
```
Then, you could just return a float instead of an integer percentage, this makes it more natural as a ratio or fraction:
```py
def gurkan_rate(name: str) -> float:
    """Returns the rate of gurkan in the name given."""
    search = re.search(r"gurk|urkan", name.lower())
    begin, end = search.span() if search else (0, 0)
    return (end - begin) / len(name)
```
Then, you don't really need a regex here.
```py
def gurkan_rate(name: str) -> float:
    """Returns the rate of gurkan in the name given."""
    for pattern in ("gurk", "urkan"):
        if pattern in name:
            return len(pattern)/len(name)
    return 0.0
```
I have no idea why that algorithm is used. Isn't a name more gurkan if it has more than one "gurk" or "urkan"?
```py
def gurkan_rate(name: str) -> float:
    """Returns the rate of gurkan in the name given."""
    if name == "":
        return 0.0
    gurkanness = 0
    for match in re.finditer("gurk|urkan", name):
        begin, end = match.span()
        gurkanness += end - begin
    return gurkanness / len(name)
```

2021-01-13 15:15 UTC, ReneganRonin approved these changes
LGTM. Good job @saiTama-max for clean code.

2021-01-13 15:15 UTC, ReneganRonin commented on README.md
> +
dunno what happened here but okay

2021-01-13 15:17 UTC, saiTama-max commented on README.md
> +
oh i dunno either

2021-01-13 15:23 UTC, Shivansh-007 reviewed
Lovellly code, just a few tinny changes are required. Thanks

2021-01-13 15:23 UTC, Shivansh-007 commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
Do we need need to use triple quotes here?

2021-01-13 15:23 UTC, Shivansh-007 commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
Hmmmm why is there a change in the pip file.lock?

2021-01-13 15:24 UTC, saiTama-max commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
hmm it was outdated

2021-01-13 15:26 UTC, ReneganRonin commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
uh wait what? did u change the version within the pipfile?

2021-01-13 15:26 UTC, saiTama-max commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
in this commit, check the build fail error c4b0dce8766b309d72477b09853d60aaddeb22f1

2021-01-13 15:27 UTC, ReneganRonin commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
nvm i realized it might have auto updated??

2021-01-13 15:27 UTC, saiTama-max commented on Pipfile.lock
> +                "sha256:0c111a2236b191422b37fe8c28b8c828ced39aab4bf5627fa5c331aeffb570d9",
i updated it with `pipenv lock`

2021-01-13 15:31 UTC, saiTama-max commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
i think yes, it will error out without them

2021-01-13 15:33 UTC, ReneganRonin commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
i think the triple quotes were used because he wanted to modify some a lil bit of space using `\\` but maybe thats just me. @saiTama-max was that your intention?

2021-01-13 15:35 UTC, saiTama-max commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
avoiding flake8 screaming for line limit crossed

2021-01-13 15:42 UTC, saiTama-max commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
alright it was just 2 characters longer so i renamed variable 2 characters less

2021-01-13 15:43 UTC, ReneganRonin commented on bot/exts/gurkan/gurkan_stats.py
> +            description = f"""About {rate}% ({gurkans}/ {len(members)})\
yeah good thing you noticed a workaround. but if thats the case? then u dont need the `\`

2021-01-13 15:45 UTC, codephile1221 requested changes
Hey, code looking good.
Just some small things to take care of.

2021-01-13 15:45 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
I think we can omit mentioning the part about color.

2021-01-13 15:45 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +    def __init__(self, bot: Bot):
```suggestion
    def __init__(self, bot: Bot) -> None::
```

2021-01-13 15:50 UTC, codephile1221 reviewed
Forgot to mention one thing.

2021-01-13 15:50 UTC, codephile1221 commented on bot/constants.py
> +    invalid = "\u274c"
suffix `emoji` as it is required by [Smart Config](https://github.com/python-discord/smartconfig), apparently. 
```suggestion
    cucumber_emoji = "\U0001f952"
    invalid_emoji = "\u274c"
```

2021-01-13 15:50 UTC, ReneganRonin commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
"whether"

2021-01-13 15:51 UTC, saiTama-max commented on bot/constants.py
> +    invalid = "\u274c"
alrighty

2021-01-13 15:51 UTC, ReneganRonin commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
> I think we can omit mentioning the part about color.

is that an optional change? i find the docstring okay or maybe thats just me

2021-01-13 15:51 UTC, ReneganRonin commented on bot/exts/gurkan/gurkan_stats.py
> +    def __init__(self, bot: Bot):
makes sense since it will return "Nothing". I will commit this

2021-01-13 15:52 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
I don't think it's really needed.
Most embeds sent by our bot use different embeds according to the situation, so I felt it is not worth mentioning.

2021-01-13 15:54 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +    def __init__(self, bot: Bot) -> None::
```suggestion
    def __init__(self, bot: Bot) -> None:
```
That was silly of me.

2021-01-13 17:02 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
@saiTama-max  what are your thoughts?

2021-01-13 17:14 UTC, saiTama-max commented on bot/exts/gurkan/gurkan_stats.py
> +        the color depending on how high the rate is.
i removed the color part so yeah, i think its sensible too because a non colored embed is meh

2021-01-13 17:55 UTC, codephile1221 requested changes

2021-01-13 17:55 UTC, codephile1221 commented on bot/exts/gurkan/gurkan_stats.py
> +    async def is_gurkan(self, ctx: Context, *, user: Union[Member, str] = None) -> None:
```suggestion
    async def is_gurkan(self, ctx: Context, *, user: Optional[Member, str] = None) -> None:
```
I missed this.

2021-01-14 04:06 UTC, saiTama-max commented on bot/exts/gurkan/gurkan_stats.py
> +    async def is_gurkan(self, ctx: Context, *, user: Union[Member, str] = None) -> None:
ooh

2021-01-15 11:00 UTC, codephile1221 approved these changes
Hello :point_right: :point_left:... 

Looks good to me!
Thank you for contributing.

2021-01-15 12:34 UTC, ReneganRonin approved these changes

2021-01-16 09:14 UTC, gustavwilliam commented
Hey @Akarys42, could you have a second look at this and see if your requested changes are addressed?

2021-01-16 09:15 UTC, gustavwilliam commented
Has anyone tested this and can confirm that it not only works, but that the rates that appear make sense?

2021-01-16 09:15 UTC, Shivansh-007 approved these changes

2021-01-16 09:15 UTC, Shivansh-007 commented on bot/exts/gurkan/gurkan_stats.py
> +RATE_DICT = {
Not required, but this could be done, instead of just having one word, we could have a list of them, and randomly choose between them.

2021-01-16 09:15 UTC, Shivansh-007 commented on bot/constants.py
> +    cucumber_emoji = "\U0001f952"
```suggestion
    gurkan_emoji = "\U0001f952"
```
Gurkan sounds better ig.

2021-01-16 09:17 UTC, v1nam commented
I have tested it, i will do it one more time rn, and about the rates, it depends on how you want them to make sense, but to me its better than using fuzzywuzzy which will show 90% on the letter `k`, which is not the case here and we are using regex, so any name that doesnt match `gurkan|urkan|gurk` will have 0, i added gurkan in the regex too because if i just use gurk and urkan, so if someone has gurkan in there names the rate will be lower

2021-01-16 09:18 UTC, codephile1221 commented on bot/constants.py
> +    cucumber_emoji = "\U0001f952"
I disagree, since it is literally the cucumber emoji and not from the set of custom gurkan emojis.

2021-01-16 09:21 UTC, v1nam commented on bot/constants.py
> +    cucumber_emoji = "\U0001f952"
yeah, it can also create confusion on what the gurkan emoji even is, it could even be the gurkan crown in the future

2021-01-16 09:29 UTC, gustavwilliam commented
It seems like this would make the steps more incremental. As long as it makes sense on most gurkan names (and non-gurkan ones), I’d be fine with doing it like this.

Could you try it with 5 random names (from our member list?) and post the results here, so I get get an overview of how it would perform.

2021-01-16 09:38 UTC, v1nam commented
sure, i will do it in a second

2021-01-16 09:45 UTC, v1nam commented
![image](https://user-images.githubusercontent.com/71541684/104808575-3f9cec80-580d-11eb-8843-cfea5aee30b1.png)
![image](https://user-images.githubusercontent.com/71541684/104808651-b1753600-580d-11eb-9d3f-d36e2a30550c.png)

2021-01-16 09:48 UTC, v1nam commented
so basically, it checks if you have `gurkan|urkan|gurk` in your name, (in that order) and then the rate will be the span of of the match, (i.e if your match is gurkan span will be 6) divided by the length of your name

2021-01-23 12:04 UTC, gustavwilliam commented
Hmmm okay. It looks slightly weird when UncomfyMelonGurkan only got 33.33% (also, round it to 33%).

2021-01-23 15:12 UTC, ReneganRonin commented
@gustavwilliam that is because i am wearing a disguise. i am actually a melon.

2021-02-01 01:30 UTC, Shivansh-007 commented
Is this ready? We have got 3 approvals on this.

2021-02-05 13:38 UTC, v1nam commented
@gustavwilliam is it necessary to round it? IMO decimals seem better :thinking:

2021-02-07 10:10 UTC, gustavwilliam commented
I mean, that precision just looks weird. I don’t like the decimals

2021-02-07 10:12 UTC, v1nam commented
Alright then, tbh I don't mind either way, and the decimals can be quite annoying sometimes

2021-02-07 10:49 UTC, Shivansh-007 approved these changes

2021-02-07 11:26 UTC, merged