Added helper function for subscribe_group and unsubscribe_group and m…
gurkult/gurkbot pull request #71
Opened 2021-01-13 11:40 UTC by Arnav-2004

…odified constats.py

2021-01-13 11:41 UTC, Arnav-2004 commented
Had to close the earlier pr because I deleted the fork. This will close issue#31

2021-01-13 14:03 UTC, codephile1221 requested changes
Hey Arnav, I'm really happy with the helper functions. There are a few more things you could do to improve it. This PR is getting close to being merged :star:

2021-01-13 14:03 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +    async def unsubscribe_group_helper(self, ctx: Context) -> None:
Everything I said above applies for unsubscribing too.

2021-01-13 14:13 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +    async def apply_role(self, ctx: Context, role_id: int, role_name: str) -> None:
Annotation doesn't match the return type.

2021-01-13 14:19 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +    async def apply_role(self, ctx: Context, role_id: int, role_name: str) -> None:
Annotation to also be fixed.

2021-01-14 11:58 UTC, ReneganRonin commented on bot/exts/utils/subscription.py
> +        elif role_check == (True, True):
looks more pythonic

2021-01-14 18:50 UTC, codephile1221 requested changes
We are nearing completion :+1:

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +                return False  # user already has the role
But it will not be required if you are passing in the role directly.

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        roles = (Roles.announcements, Roles.polls)
This tuple can be passed in as an argument

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        )
Use a loop to create this tuple.

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        )
Actually, you can create a dictionary using a comprehension with the role as the key and the result of `apply_role` as the value. This will be useful below :point_down:

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +            await ctx.send(content=ctx.author.mention, embed=embed)
You can achieve this in a single block without checking for each condition.
Construct the "You've subscribe to {role1} and {role2}" according to the `role_check` dictionary.

2021-01-14 18:50 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +        await self.subscribe_group_helper(ctx)
```suggestion
    async def subscribe_group(self, ctx: Context) -> None:
        """Subscribe to announcements and polls notifications by assigning yourself the role."""
        roles = (the tuple)
        await self.subscribe_group_helper(ctx, roles)
```
(according to this  [proposed change](https://github.com/gurkult/gurkbot/pull/71/files#diff-f3b2625c9076cca23a5c94b8b7d62f99df3830a77e0707be8809fcb7c9636250R77)

2021-02-06 11:49 UTC, Shivansh-007 requested changes

2021-03-09 06:00 UTC, RohanJnr commented
@Arnav-2004 are you planning on continuing this PR?

2021-03-11 11:14 UTC, Arnav-2004 commented
> @Arnav-2004 are you planning on continuing this PR?

Yes, after 18th March I will be working on it. Because of school exams I am not able to work on it.

2021-03-13 07:35 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +                color=Colours.green,
Let's wait for #30 then

2021-03-13 08:30 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +        roles = (Roles.announcements, Roles.polls)
Not anymore because I am using `roles = (ctx.guild.get_role(Roles.announcements), ctx.guild.get_role(Roles.polls))`

2021-03-13 16:26 UTC, Shivansh-007 requested changes
Quick review.

2021-03-13 16:26 UTC, Shivansh-007 commented on bot/constants.py
> +    confirmation_emoji = "<:confirmation:794231332770938901>"
This is the wrong emoji `Id` and it is not present in Gurkbot emoji server also. Please do the required changes.

2021-03-13 16:26 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        """Adding Roles and returning True otherwise False."""
```suggestion
        """Adding roles and returning `True` otherwise `False`."""
```
You are pointing towards some code of python, or keywords so these always be enclosed with back ticks. Apply this change at the other required places too.

Another point, this docstring doesn’t seem to explain anything what the function does, we can understand it returns True/False by the return type annotation but what cases are they returned?

2021-03-13 16:26 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        """Removing Roles and returning True otherwise False."""
Look above.

2021-03-17 07:42 UTC, codephile1221 requested changes

2021-03-17 07:42 UTC, codephile1221 commented on bot/exts/utils/subscription.py
> +            ctx.guild.get_role(Roles.polls),
I'm thinking about making a separate category for subscribeable roles under [`Roles` in `constants.py`]( https://github.com/gurkult/gurkbot/blob/7cfcc2d856393f9b91caa7babb3213e928cbb835/bot/constants.py#L43-L44 ).
To make more roles subscribeable, all we will need to do is specify the role to constants.py .

I will need to think more about this though- as we could also use a YAML for storing all configuration and utilise aliasing.

2021-03-24 13:10 UTC, ShakyaMajumdar commented on bot/exts/utils/subscription.py
> +                role_lst.append(role)
This looks like a lot of work for just filtering out roles that weren't applied, and I believe you should just be able to do:
```py
role_lst = [role.name for role in roles if await self.apply_role(ctx, i)]
```

2021-03-24 13:13 UTC, Shivansh-007 requested changes
Quick review, will give it a full review probably tomorrow.

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        """Unsubscribe to announcements and polls notifications by assigning yourself the role."""
This is probably a comma splice and there are two roles so `role` should be plural.
```suggestion
        """Unsubscribe to announcements and polls notifications, by assigning yourself the roles."""
```
Mention this change in other similar places too.

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +                role_lst.append(role)
We can possibly make a list comprehension for this.

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +            role_check += (await self.de_apply_role(ctx, i),)
We can possibly make a list comprehension for this.

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +                role_lst.append(role)
We can possibly make a list comprehension for this.

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +            role_check += (await self.apply_role(ctx, i),)
We can possibly make a tuple comprehension for this.

eg: `role_check = (await self.apply_role(ctx, role) for role in roles)`

2021-03-24 13:13 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +            ctx.guild.get_role(Roles.polls),
Instead of getting role at multiple places, you can just get them in `__init__`.

2021-03-24 14:49 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +            role_check += (await self.apply_role(ctx, i),)
These lines have been completely removed.

2021-03-25 07:57 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +            ctx.guild.get_role(Roles.polls),
I will just make a different function for the roles so that the `__init__` doesn't look all cramped up and a dedicated function for just getting the roles might help in future if we have more roles to subscribe to.

2021-03-25 09:29 UTC, Akarys42 requested changes
Just a code review for now. It looks pretty good, couple of little things.

2021-03-25 09:29 UTC, Akarys42 commented on bot/exts/utils/subscription.py
> +    async def de_apply_role(self, ctx: Context, role_name: Role) -> bool:
Why not 
```suggestion
    async def remove_role(self, ctx: Context, role_name: Role) -> bool:
```

2021-03-25 09:29 UTC, Akarys42 commented on bot/exts/utils/subscription.py
> +        """Returns `True` if role is successfully removed otherwise it returns `False`."""
Typo
```suggestion
        """Returns `True` if role was successfully removed otherwise it returns `False`."""
```

2021-03-25 09:29 UTC, Akarys42 commented on bot/exts/utils/subscription.py
> +        """Returns `True` if role is successfully added otherwise it returns `False`."""
Same as above
```suggestion
        """Returns `True` if role was successfully added otherwise it returns `False`."""
```

2021-03-25 12:30 UTC, Shivansh-007 requested changes
Code looks good, just a few changes and it should be ready for merge then :D

2021-03-25 12:30 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        """Returns a `tuple` with all the roles that you can subscribe/unsubscribe to."""
I am not a fan of adding `Returns a 'tuple'` here, we can of course see that from the return type annotations.

We can do something like this:
```suggestion
        ""Gets the polls and announcements roles from the guild of the context."""
```

2021-03-25 12:30 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +        await self.unsubscribe_helper(ctx, Roles.polls)
```suggestion
    @group(name="subscribe", invoke_without_command=True)
    async def subscribe_group(self, ctx: Context) -> None:
        """Subscribe to announcements and polls notifications, by assigning yourself the roles."""
        await self.subscribe_group_helper(ctx)
    
    @subscribe_group.command(name="announcements", aliases=("announcement",))
    async def announcements_subscribe(self, ctx: Context) -> None:
        """Subscribe to announcements by assigning yourself the role."""
        await self.subscribe_helper(ctx, Roles.announcements)
    
    @subscribe_group.command(name="polls", aliases=("poll",))
    async def polls_subscribe(self, ctx: Context) -> None:
        """Subscribe to polls by assigning yourself the role."""
        await self.subscribe_helper(ctx, Roles.polls)
    
    # ---------------------------------------------------------------------------------------------
    
    @group(name="unsubscribe", invoke_without_command=True)
    async def unsubscribe_group(self, ctx: Context) -> None:
        """Unsubscribe to announcements and polls notifications, by removing your roles."""
        await self.unsubscribe_group_helper(ctx)
    
    @unsubscribe_group.command(name="announcements", aliases=("announcement",))
    async def announcements_unsubscribe(self, ctx: Context) -> None:
        """Unsubscribe to announcements by removing your role."""
        await self.unsubscribe_helper(ctx, Roles.announcements)
    
    @unsubscribe_group.command(name="polls", aliases=("poll",))
    async def polls_unsubscribe(self, ctx: Context) -> None:
        """Unsubscribe to polls by removing your role."""
        await self.unsubscribe_helper(ctx, Roles.polls)
```

We can probably keep it cleaned up like this, so it is easy to figure out the groups at one look.

2021-03-25 12:30 UTC, Shivansh-007 commented on bot/exts/utils/subscription.py
> +            embed = Embed(
Similar embeds are being created at lots of places in the code, you can preferably create a helper method for creating and sending the embed.
```py
async def embed_helper(self, ctx, type, msg):
            # if statements for `color`, `emoji`, `text`
            embed = Embed(
                title=f"{emoji} {text}",
                description=f"You're {text.lower()} to {ctx.guild}'s {msg}",
                color=color,
            )
```

2021-03-25 13:07 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +            embed = Embed(
We can wait for #30

2021-03-27 10:15 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-03-27 14:08 UTC, RohanJnr requested changes

2021-03-27 14:08 UTC, RohanJnr commented on bot/exts/utils/subscription.py
> +    async def unsubscribe_group_helper(self, ctx: Context) -> None:
There a lot of similarities between `unsubscribe_group_helper` and `subscribe_group_helper` commands, try to use 1 function to accomplish both if you can.

2021-03-27 14:08 UTC, RohanJnr commented on bot/exts/utils/subscription.py
> +    async def subscribe_helper(self, ctx: Context, role_id: int) -> None:
lot of similarity between `subscribe_helper` and `unsubscribe_helper`, try to accomplish the same with 1 function if you can.

2021-03-27 14:12 UTC, RohanJnr commented
Also, I see a problem with the function names and doc strings, just for an example:
function: `subscribe_group_helper`
This name does not make anything clear, a better name would be `_subscribe` and the doc string could be 
`Subscribe for announcements and polls.`
the current docstring `Helper function for unsubscribe_group. Sends embed for role unsubscription.` does not tell the actual functionality of the function, the function is also removing roles which is the main thing not mentioned in the doc string

2021-04-03 16:37 UTC, RohanJnr requested changes

2021-04-03 16:37 UTC, RohanJnr commented on bot/exts/utils/subscription.py
> +        return roles
```suggestion
        return (
            ctx.guild.get_role(Roles.announcements),
            ctx.guild.get_role(Roles.polls),
        )
```

2021-04-22 09:12 UTC, gustavwilliam requested changes
Thanks! This is only a code review and I have a few comments

2021-04-22 09:12 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +        role_lst = [role.name for role in roles if await func(ctx, role)]
I don't quite follow what this does.

2021-04-22 09:12 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +            )  # stores a string which tells what role(s) is/are added to or removed from the user
```suggestion
            )  # Stores a string which tells what role(s) is/are added to or removed from the user
```

2021-04-22 09:12 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +        )
```suggestion
        embed = Embed(
            title=f"{Emojis.confirmation_emoji} Subscribe List",
            description=f"- {"\n- ".join(role.name for role in roles)}",
            color=Colours.green,
        )
```
You shouldn't need the `escape` variable here

2021-04-22 09:12 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +            description=f"- {escape.join(role.name for role in roles)}",
```suggestion
            description=f"- {escape.join(role.name for role in roles)}",  # Creates bullet list
```
A comment could help clarify what this does

2021-04-23 14:20 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +        role_lst = [role.name for role in roles if await func(ctx, role)]
@gustavwilliam 
So, basically 'func' can be 'apply_role' or 'remove_role'. If 'func' is 'apply_role', then the 'role_lst' variable will store all the roles which have value as 'True' which was returned by the 'apply_role' function. Suppose you don't have any roles currently and you want to subscribe to polls, then after running `!sub polls` the 'role_lst' variable will store 'polls'. Similarly with the 'func' being 'remove_role'.

2021-04-23 14:32 UTC, gustavwilliam commented on bot/exts/utils/subscription.py
> +        role_lst = [role.name for role in roles if await func(ctx, role)]
Hmm, alright. I feel like this line is trying to accomplish two things:
- Apply the roles
- Return a list of roles that were applied

I'd recommend braking this up or at least clarifying what's going on. In this case, I'll be happy with a clear and concise comment that explains what this line does.

2021-04-23 15:05 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +        role_lst = [role.name for role in roles if await func(ctx, role)]
Alright!

2021-04-24 06:34 UTC, Arnav-2004 commented on bot/exts/utils/subscription.py
> +        role_name = ctx.guild.get_role(role_id)
The `get_roles()` function returns a tuple of all the roles you can subscribe too. I only wanted one role specified by the user that is why I am doing this otherwise I could do something like: making the `get_roles()` function return a dictionary and store id as key and role as value.

2021-06-18 21:13 UTC, gustavwilliam commented
Let's do it.

2021-06-18 21:13 UTC, merged