Add Contributing Guide.
gurkult/gurkbot pull request #72
Opened 2021-01-13 11:41 UTC by Shivansh-007

Explains the rules of contributing, how to work with git on `Pycharm` and `Terminal`, and basics on git.

Adapted from Python Discord.

2021-01-14 11:22 UTC, Shivansh-007 commented
@gustavwilliam Can you have a look at this?

2021-01-14 18:00 UTC, vivax3794 requested changes

2021-01-15 01:18 UTC, ReneganRonin commented
Hello. Good morning. I would like to kindly reject the idea of adding a guide on how to use git for PyCharm or whatever specific editor in mind. This will only prevent people to look at the official documentation of their editor or of the feature they are using for their editor and will only make this Contributing Guide somewhat repetitive and constrained. 
**I only like the git command instructions _for the commandline_ because git is supposedly used on the commandline.**

This was discussed with other dev contributors and we made this conclusion to not include it, hence, the aforementioned ^.

2021-01-15 10:33 UTC, Shivansh-007 commented
@ReneganRonin and @vivax3794 I have mentioned those changes, Can you have a look again?

2021-01-19 07:34 UTC, vivax3794 requested changes
Just a minor thing

2021-01-20 15:23 UTC, vivax3794 approved these changes
LGTM

2021-01-22 05:42 UTC, Shivansh-007 commented
@ReneganRonin Can you have a look at it ?

2021-01-22 06:11 UTC, ReneganRonin approved these changes
Looks good to me. 😄

2021-01-23 11:57 UTC, gustavwilliam requested changes
It's pretty pydis-y

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +Learn how to obtain the ID of a server, channel or role **[here](https://pythondiscord.com/pages/contributing/setting-test-server-and-bot-account/#setting-up-a-test-server).**
I'm not a fan of linking to pydis everywhere.

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +
Don't we have Dev alerts as well?

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +Now that you have everything setup, it is finally time to make changes to the bot! If you have not yet read the contributing guidelines, now is a good time. Contributions that do not adhere to the gu
We don't have any contributing guidelines, right?

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +Click [here](https://pythondiscord.com/pages/contributing/working-with-git/ "here") to see the basic Git workflow when contributing to one of our projects
Once again, i don't like that we're linking to pydis everywhere.

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +2. Your pull request must solve an issue created or approved by a staff member. These will be labelled with the `approved` label. Feel free to suggest issues of your own, which staff can review for a
We don't have an "approved" label, nor do we have the concept of staff. A lord gurkan must approve it before getting started. That's all we care about.

2021-01-23 11:57 UTC, gustavwilliam commented on CONTRIBUTING.md
> +3. **No force-pushes** or modifying the Git history in any way.
I don't like this rule. It can be great to modify the gif history in some cases. Mostly, this just applies to the master branch and not the feature branches.

2021-01-28 00:45 UTC, Shivansh-007 commented
@gustavwilliam Mentioned the requested changes!

2021-03-08 23:44 UTC, Shivansh-007 commented on CONTRIBUTING.md
> +# Rules
What do you mean by ”doesn’t sound right"?

2021-03-09 05:09 UTC, RandomDev26 commented on CONTRIBUTING.md
> +# Rules
Rules conveys the wrong feeling. It seems out of place compared to the rest of the guide.

2021-03-09 06:08 UTC, Shivansh-007 commented on CONTRIBUTING.md
> +# Rules
Hmm, am not sure about this. Would like to hear other people's opinions on this.

2021-03-09 06:28 UTC, codephile1221 commented on CONTRIBUTING.md
> +# Rules
I agree with @RandomDev26. "Guidelines" or "specifications" sound more welcoming.

2021-03-09 08:37 UTC, Shivansh-007 commented on CONTRIBUTING.md
> +# Rules
Done @codephile1221 @RandomDev26 !

2021-03-09 15:46 UTC, RandomDev26 approved these changes
LGTM!

2021-04-06 08:40 UTC, codephile1221 requested changes
Hey @Shivansh-007, minor changes.

2021-04-06 08:40 UTC, codephile1221 commented on CONTRIBUTING.md
> +6. [Work with git to make changes](#Working-with-Git)
```suggestion
6. [Working with git to make changes](#Working-with-Git)
```

2021-04-06 08:40 UTC, codephile1221 commented on CONTRIBUTING.md
> +   \#dev-log
Why is this not on a new line?
Also, do you feel it's necessary to add #dev-alerts too?

2021-04-06 08:40 UTC, codephile1221 commented on CONTRIBUTING.md
> +Notably, version control of our projects is done using Git and Github. It can be intimidating at first, so feel free to ask for any help in the server.
```suggestion
Notably, version control of our projects is done using Git and GitHub. It can be intimidating at first, so feel free to ask for any help in the server.
```

2021-04-06 08:40 UTC, codephile1221 commented on CONTRIBUTING.md
> +2. Your pull request must solve an issue created or approved by a gurkan lord. Feel free to suggest issues of your own, which lords can review for approval.
```suggestion
2. Your pull request must solve an issue created or approved by a Gurkan Lord. Feel free to suggest issues of your own, which lords can review for approval.
```

2021-04-06 08:40 UTC, codephile1221 commented on CONTRIBUTING.md
> +4. Each environment variable is on its own line, with the variable and the value separated by a = sign.
```suggestion
4. Each environment variable is on its own line, with the variable and the value separated by a `=` sign.
```

2021-04-06 09:58 UTC, Shivansh-007 commented on CONTRIBUTING.md
> +   \#dev-log
Yeah will add dev alerts, and the new line was a typo, I missed out the `n`

2021-04-06 11:46 UTC, Akarys42 commented
This is a plain copy pasta of the Python Discord Guide for Sir Lancebot, without any kind of attribution, while the guide itself is all rights reserved. Your commit messages aren't descriptive enough either. I'm sorry but this isn't acceptable.

2021-04-06 11:46 UTC, closed without merging