Add an Auto Config system and have a default config file.
gurkult/gurkbot pull request #73
Opened 2021-01-14 11:01 UTC by Inheritanc-e

Fixes Issue [Issue 50](https://github.com/gurkult/gurkbot/issues/50l)

Created an auto-config system, added a config folder which contains the config list and the default config files for the bot, modified `constants.py` to use the config files to store channel and role ids. Used collections.namedtuple for channel and role constants. Modified return statements in `__init__.py.` Synced the project to use modified `constants.py`

2021-01-14 11:20 UTC, Shivansh-007 requested changes

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/config/config-list.yaml
> +
Add the un-optional channels here too, and when the bot goes over them, it asks the user whether they want to create the un-optional channels or not.
Same for the roles.

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/constants.py
> +class Gurkbot:
```suggestion
class Client:
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/constants.py
> +ERROR_REPLIES = [
Why did u shift the `error replies` to `constants.py` from the `yaml` file?
See fisher's comments on Error Handler Pr

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/constants.py
> +Channels = namedtuple(
Using a class for this looks better and more readable and easier to understand.

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +        if not self.bot.get_guild(int(os.getenv('Guild_ID'))):
```suggestion
        """Check's if the guild exists or not, if not then raises NotFound."""
        if not self.bot.get_guild(int(os.getenv('Guild_ID'))):
```
There shouldn't be a empty space in `def` functions.

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/constants.py
> +class Colour(Enum):
Use `NamedTuple`

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +    """A cog responsible for constructing config files"""
```suggestion
    """A cog responsible for constructing config files."""
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +        ) if not discord.utils.get(guild.channels, name=x)]
```suggestion
        channels = [x for x in self.required()['Roles'].keys() 
        if not discord.utils.get(guild.channels, name=x)]
```
Keep the brackets on the same line.

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +    async def create_(self) -> None:
```suggestion
    async def _create(self) -> None:
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                    await guild.create_role(name=r)
```suggestion
                for role in self.check()['Roles']:
                    await guild.create_role(name=role)
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                logger.info('Successfully created all the roles and roles')
```suggestion
                logger.info('Successfully created all the roles')
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                    await guild.create_text_channel(name=c)
```suggestion
                for channel in self.required()['Channels']:
                    await guild.create_text_channel(name=channel)
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                logger.info('Successfully created all the roles and channels!')
```suggestion
                logger.info('Successfully created all the roles.')
```
Isn't this only making the channels?

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                    await guild.create_role(name=r)
```suggestion
                for channel in self.required()['Channels']:
                    await guild.create_text_channel(name=channel)

                for role in self.check()['Roles']:
                    await guild.create_role(name=role)
```

2021-01-14 11:20 UTC, Shivansh-007 commented on bot/exts/backend/auto_config.py
> +                logger.info('Successfully created all the roles and channels and roles!')
```suggestion
                logger.info('Successfully created all the roles and channels!')
```

2021-01-14 11:24 UTC, Inheritanc-e commented on bot/config/config-list.yaml
> +
It is pretty obvious that the channels and roles that have not been marked as optional are mandatory.

2021-01-14 11:25 UTC, Inheritanc-e commented on bot/constants.py
> +class Gurkbot:
Having the class as the bot's name would make more sense IMO.

2021-01-14 11:25 UTC, Inheritanc-e commented on bot/constants.py
> +ERROR_REPLIES = [
Gotcha.

2021-01-14 11:26 UTC, Inheritanc-e commented on bot/constants.py
> +Channels = namedtuple(
If we use a class then we would have to insert them again. But we shouldn't have to do that because it already exists in the config, file.

2021-01-14 11:27 UTC, Inheritanc-e commented on bot/constants.py
> +class Colour(Enum):
Enum is more suited for this rather than named tuple.

2021-01-14 11:27 UTC, Shivansh-007 commented on bot/constants.py
> +Channels = namedtuple(
Instead of using `namedtuple`, why not pick them like we did for the environment variables?

2021-01-14 11:28 UTC, Shivansh-007 commented on bot/constants.py
> +class Gurkbot:
What if the name of the bot changes in future?

2021-01-14 11:28 UTC, Shivansh-007 commented on bot/config/config-list.yaml
> +
But, to test the github category we need the dev categories, so hence we need them.

2021-01-14 11:44 UTC, Inheritanc-e commented on bot/constants.py
> +Channels = namedtuple(
What do you mean?

2021-01-14 11:45 UTC, Inheritanc-e commented on bot/config/config-list.yaml
> +
We need them hence it's set to false.

2021-01-14 11:45 UTC, Inheritanc-e commented on bot/constants.py
> +class Gurkbot:
Then we change the name of the class.

2021-01-14 11:47 UTC, Inheritanc-e commented on bot/constants.py
> +class Colour(Enum):
And named tuple aren't `iterable`.

2021-01-14 12:03 UTC, Inheritanc-e commented on bot/config/config-list.yaml
> +
And if we require them to be mandatory then we could just completely remove them from the `config-list.yaml`

2021-01-14 12:06 UTC, Inheritanc-e commented on bot/exts/backend/auto_config.py
> +                logger.info('Successfully created all the roles and channels!')
If the code reached up the `else` statement then it means that the server doesn't have the channels configured nor does it have the roles configured.

2021-01-14 16:01 UTC, codephile1221 commented on bot/constants.py
> +class Colour(Enum):
Good call, enums are suited for this role.

2021-01-14 16:04 UTC, codephile1221 commented on bot/constants.py
> +class Gurkbot:
Do we really need this class? Is it related to how `auto-config` works?
`Gurkbot` doesn't feel like an apt name.

2021-01-14 16:09 UTC, codephile1221 commented on bot/constants.py
> +Channels = namedtuple(
Not sure about this one, chief.
We should discuss this on the server.  Readability is lost.
Btw, you can use `typing.NamedTuple` to create a named tuple and I feel that'd produce more readable code.

2021-01-14 16:16 UTC, Inheritanc-e commented on bot/constants.py
> +class Gurkbot:
I mean would it not make sense to have the tokens and prefix of the bot in a single class?

2021-01-15 10:39 UTC, Shivansh-007 commented on bot/config/config-list.yaml
> +
> We need them hence it's set to false.

the dev-gurkbot, etc. are required for github category and I don't see them here.

2021-01-15 10:39 UTC, Shivansh-007 commented on bot/constants.py
> +class Gurkbot:
Yeah, it would keep the `client` constants together

2021-01-15 10:41 UTC, Shivansh-007 commented on bot/constants.py
> +Channels = namedtuple(
Yeah, I agree with @codephile1221, the readability is lost, @gustavwilliam whats your say on this?

2021-01-15 10:41 UTC, Shivansh-007 commented on bot/constants.py
> +class Colour(Enum):
Hmmm, alright.

2021-01-15 11:02 UTC, codephile1221 commented on bot/constants.py
> +Channels = namedtuple(
TBH, readability doesn't matter much since you can look at the original config file.

2021-01-15 13:36 UTC, Inheritanc-e commented on bot/config/config-list.yaml
> +
Well they aren't needed for the bot as of now. So....

2021-01-15 13:37 UTC, Inheritanc-e commented on bot/constants.py
> +class Gurkbot:
Client can mean many things.

2021-01-15 13:38 UTC, Inheritanc-e commented on bot/constants.py
> +Channels = namedtuple(
How is readability lost?
This is very much understandable, the first parameter of named tuples are keys and the default keyword takes a tuple which are the values for those keys going from left to right.

2021-01-28 07:38 UTC, Shivansh-007 commented on bot/constants.py
> +Channels = namedtuple(
Which is easier to understand, the former way or the yours?

2021-01-28 07:45 UTC, Inheritanc-e commented on bot/constants.py
> +Channels = namedtuple(
Mine is very much understandable, if you wish to see the ids then the config file exists for that,  and you would not understand mine only if you don't know how namedtuple works.

2021-02-07 06:19 UTC, Shivansh-007 commented
@Inheritanc-e Can you fix the conflicts in here?

2021-06-18 21:18 UTC, RohanJnr commented
is this PR still WIP?

2021-12-25 15:54 UTC, gustavwilliam commented
> is this PR still WIP?

@RohanJnr definitely doesn't seem so

2022-01-18 07:24 UTC, gustavwilliam commented
@Inheritanc-e Thanks for all the work you did with this. Sadly it doesn't seem like it'll be finished, so I'm closing the PR.

The code is pretty outdated compared to the rest of the bot today, but if you would like to resume something like this in the future, feel free to ping me.

2022-01-18 07:24 UTC, closed without merging